<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $entes = [
            // 1 al 88: Entes Estatales / Secretarías / Fideicomisos (Nivel de Gobierno Estatal, ej: 1)
            ['id' => 1, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE GOBIERNO', 'siglas' => null],
            ['id' => 2, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE HACIENDA', 'siglas' => null],
            ['id' => 3, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE DESARROLLO URBANO Y ECOLOGÍA', 'siglas' => null],
            ['id' => 4, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE COMUNICACIONES Y OBRAS PÚBLICAS', 'siglas' => null],
            ['id' => 5, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE EDUCACIÓN Y DEPORTE', 'siglas' => null],
            ['id' => 6, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE TRABAJO Y PREVISIÓN SOCIAL', 'siglas' => null],
            ['id' => 7, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE DESARROLLO HUMANO Y BIENESTAR COMÚN', 'siglas' => null],
            ['id' => 8, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE SALUD', 'siglas' => null],
            ['id' => 9, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE INNOVACIÓN Y DESARROLLO ECONÓMICO', 'siglas' => null],
            ['id' => 10, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE DESARROLLO RURAL', 'siglas' => null],
            ['id' => 11, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE LA FUNCIÓN PÚBLICA', 'siglas' => null],
            ['id' => 12, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE SEGURIDAD PÚBLICA', 'siglas' => null],
            ['id' => 13, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FISCALÍA GENERAL DEL ESTADO', 'siglas' => null],
            ['id' => 14, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE TURISMO', 'siglas' => null],
            ['id' => 15, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE CULTURA', 'siglas' => null],
            ['id' => 16, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA DE PUEBLOS Y COMUNIDADES INDÍGENAS', 'siglas' => null],
            ['id' => 17, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN GENERAL DE COMUNICACIÓN SOCIAL', 'siglas' => null],
            ['id' => 18, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN DE ASESORES Y PROYECTOS ESPECIALES', 'siglas' => null],
            ['id' => 19, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN DE DESARROLLO MUNICIPAL', 'siglas' => null],
            ['id' => 20, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN DE RELACIONES PÚBLICAS', 'siglas' => null],
            ['id' => 21, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'REPRESENTACIÓN DEL GOBIERNO DEL ESTADO EN LA CIUDAD DE MÉXICO', 'siglas' => null],
            ['id' => 22, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN DE EJECUTIVA EN CIUDAD JUÁREZ', 'siglas' => null],
            ['id' => 23, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN DE POLÍTICA DIGITAL', 'siglas' => null],
            ['id' => 24, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COMISIÓN ESTATAL PARA LOS PUEBLOS INDÍGENAS', 'siglas' => null],
            ['id' => 25, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'DESPACHO DE LA C. GOBERNADORA', 'siglas' => null],
            ['id' => 26, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COORDINACIÓN GABINETE', 'siglas' => null],
            ['id' => 27, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'DIF DESARROLLO INTEGRAL DE LA FAMILIA', 'siglas' => null],
            ['id' => 28, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DE LAS MUJERES', 'siglas' => null],
            ['id' => 29, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DE LA JUVENTUD', 'siglas' => null],
            ['id' => 30, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DEL DEPORTE Y CULTURA FÍSICA', 'siglas' => null],
            ['id' => 31, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'PENSIONES CIVILES DEL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 32, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SERVICIOS DE SALUD DE CHIHUAHUA', 'siglas' => null],
            ['id' => 33, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DE SALUD', 'siglas' => null],
            ['id' => 34, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SERVICIOS EDUCATIVOS DEL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 35, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'EL COLEGIO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 36, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COLEGIO DE BOHILLERES DEL ESTADO DE CHIHUAHUA', 'siglas' => 'COBACH'],
            ['id' => 37, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COLEGIO DE EDUCACIÓN PROFESIONAL TÉCNICA DEL ESTADO DE CHIHUAHUA', 'siglas' => 'CONALEP'],
            ['id' => 38, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COLEGIO DE ESTUDIOS CIENTÍFICOS Y TECNOLÓGICOS DEL ESTADO DE CHIHUAHUA', 'siglas' => 'CECYTECH'],
            ['id' => 39, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DE EDUCACIÓN PARA LOS ADULTOS', 'siglas' => 'ICHEA'],
            ['id' => 40, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE DE INFRAESTRUCTURA FÍSICA EDUCATIVA', 'siglas' => 'ICHIFE'],
            ['id' => 41, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO DE CAPACITACIÓN PARA EL TRABAJO DEL ESTADO DE CHIHUAHUA', 'siglas' => 'ICATECH'],
            ['id' => 42, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE CHIHUAHUA', 'siglas' => 'UTCH'],
            ['id' => 43, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE CIUDAD JUÁREZ', 'siglas' => 'UTCJ'],
            ['id' => 44, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE LA JUNTA', 'siglas' => null],
            ['id' => 45, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE TIERRAS ALTAS', 'siglas' => null],
            ['id' => 46, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE CAMARGO', 'siglas' => 'UTCAM'],
            ['id' => 47, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE PARRAL', 'siglas' => 'UTP'],
            ['id' => 48, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE PAQUIMÉ', 'siglas' => 'UT PAQUIMÉ'],
            ['id' => 49, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE PASO DEL NORTE', 'siglas' => 'UTPN'],
            ['id' => 50, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE CHIHUAHUA SUR', 'siglas' => 'UTCH SUR'],
            ['id' => 51, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD POLITÉCNICA DE CHIHUAHUA', 'siglas' => 'UPCH'],
            ['id' => 52, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD PEDAGÓGICA NACIONAL DEL ESTADO DE CHIHUAHUA', 'siglas' => 'UPNECH'],
            ['id' => 53, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD POLITÉCNICA DE LA TARAHUMARA', 'siglas' => 'UPT'],
            ['id' => 54, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE GUACHOCHI', 'siglas' => 'UTG'],
            ['id' => 55, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD TECNOLÓGICA DE MEOQUI', 'siglas' => 'UTM'],
            ['id' => 56, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'CASA DE LAS ARTESANÍAS DEL ESTADO DE CHIHUAHUA', 'siglas' => 'CASART'],
            ['id' => 57, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'CENTRO DE INFORMACIÓN ECONÓMICA Y SOCIAL', 'siglas' => 'CIES'],
            ['id' => 58, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'PROMOTORA PARA EL DESARROLLO ECONÓMICO DE CHIHUAHUA', 'siglas' => 'PRODECH'],
            ['id' => 59, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO DE APOYO AL DESARROLLO TECNOLÓGICO', 'siglas' => 'INADET'],
            ['id' => 60, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COMISIÓN ESTATAL DE VIVIENDA, SUELO E INFRAESTRUCTURA DE CHIHUAHUA', 'siglas' => 'COESVI'],
            ['id' => 61, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'JUNTA CENTRAL DE AGUA Y SANEAMIENTO DEL ESTADO DE CHIHUAHUA', 'siglas' => 'JCAS'],
            ['id' => 62, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'OPERADORA DE TRANSPORTE VIVEBÚS CHIHUAHUA', 'siglas' => 'OTV'],
            ['id' => 63, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'CONSEJO ESTATAL DE POBLACIÓN', 'siglas' => 'COESPO'],
            ['id' => 64, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SISTEMA ESTATAL DE PROTECCIÓN INTEGRAL DE NIÑAS, NIÑOS Y ADOLESCENTES', 'siglas' => 'SIPINNA'],
            ['id' => 65, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PARA EL DESARROLLO FORESTAL DEL ESTADO DE CHIHUAHUA', 'siglas' => 'FIDEFOR'],
            ['id' => 66, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO FONDO SOCIAL PARA EL PARQUE INDUSTRIAL CHIHUAHUA', 'siglas' => null],
            ['id' => 67, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO DE TRAMO CARRETERO VÍA CORTA A PARRAAL', 'siglas' => null],
            ['id' => 68, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO EXPO-CHIHUAHUA', 'siglas' => null],
            ['id' => 69, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO ESTATAL PARA EL FOMENTO DE LAS ACTIVIDADES PRODUCTIVAS EN EL ESTADO DE CHIHUAHUA', 'siglas' => 'FIDEAPECH'],
            ['id' => 70, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PROGRAMA ESPECIAL DE FINANCIAMIENTO A LA VIVIENDA PARA EL MAGISTERIO DEL ESTADO DE CHIHUAHUA', 'siglas' => 'FOVI'],
            ['id' => 71, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO IRREVOCABLE DE ADMINISTRACIÓN Y FUENTE DE PAGO NO. 851-00287 (FIDEICOMISO DE AUTOPISTAS DE CUOTA)', 'siglas' => null],
            ['id' => 72, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO FONDO DE DEPOSITOS DE TRABAJADORES CONTRATADOS A COMISION DE LA SECRETARIA DE HACIENDA', 'siglas' => null],
            ['id' => 73, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO FONDO DE COMPENSACIÓN A VICTIMAS', 'siglas' => null],
            ['id' => 74, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO CENTRO DE IMPULSO SOCIAL Y EMPRESARIAL (CISE)', 'siglas' => null],
            ['id' => 75, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO FONDO DE RETIRO Y JUBILACIÓN DE LOS TRABAJADORES DEL GOBIERNO DEL ESTADO', 'siglas' => null],
            ['id' => 76, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO TURÍSTICO BARRANCAS DEL COBRE', 'siglas' => null],
            ['id' => 77, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO AH CHIH!', 'siglas' => null],
            ['id' => 78, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO DE PROTECCIÓN CIVIL DEL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 79, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PARA EL DESARROLLO URBANO DE CIUDAD JUÁREZ', 'siglas' => 'FIDEURB'],
            ['id' => 80, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FONDO SOCIAL DE NOGALEROS', 'siglas' => null],
            ['id' => 81, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PUBLICO PARA LA ADMINISTRACION DE FONDOS DEL PROGRAMA PROYECTOS PRODUCTIVOS EN EL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 82, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO REVITALIZACIÓN DEL CENTRO HISTÓRICO DE LA CIUDAD DE CHIHUAHUA', 'siglas' => null],
            ['id' => 83, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PRIVADO IMPULSO AGROPECUARIO', 'siglas' => null],
            ['id' => 84, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PARA LA OPERACIÓN DEL PROYECTO DE TRANSPORTE INTEGRADO VIVEBUS EN LA CIUDAD DE CHIHUAHUA', 'siglas' => null],
            ['id' => 85, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO CAUSA DE LA POLICÍA CHIHUAHUENSE', 'siglas' => null],
            ['id' => 86, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO MAQUILADORA GUADALUPE', 'siglas' => null],
            ['id' => 87, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PRIVADO METROBÚS JUÁREZ', 'siglas' => null],
            ['id' => 88, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FIDEICOMISO PRIVADO ASOCIACIÓN PÚBLICO PRIVADA DE ALUMBRADO PÚBLICO DE CHIHUAHUA', 'siglas' => null],
            
            // 89 al 101: Poder Legislativo, Judicial, Órganos Autónomos (Nivel Estatal)
            ['id' => 89, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'H. CONGRESO DEL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 90, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'AUDITORÍA SUPERIOR DEL ESTADO DE CHIHUAHUA', 'siglas' => 'ASE'],
            ['id' => 91, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'TRIBUNAL SUPERIOR DE JUSTICIA DEL ESTADO DE CHIHUAHUA', 'siglas' => 'TSJ'],
            ['id' => 92, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'CONSEJO DE LA JUDICATURA DEL ESTADO DE CHIHUAHUA', 'siglas' => null],
            ['id' => 93, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FONDO DE APOYO A LA ADMINISTRACIÓN DE JUSTICIA', 'siglas' => null],
            ['id' => 94, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO ESTATAL ELECTORAL DE CHIHUAHUA', 'siglas' => 'IEE'],
            ['id' => 95, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'COMISIÓN ESTATAL DE LOS DERECHOS HUMANOS CHIHUAHUA', 'siglas' => 'CEDH'],
            ['id' => 96, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'INSTITUTO CHIHUAHUENSE PARA LA TRANSPARENCIA Y ACCESO A LA INFORMACIÓN PÚBLICA', 'siglas' => 'ICHITAIP'],
            ['id' => 97, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'TRIBUNAL ESTATAL ELECTORAL DE CHIHUAHUA', 'siglas' => 'TEE'],
            ['id' => 98, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD AUTÓNOMA DE CHIHUAHUA', 'siglas' => 'UACH'],
            ['id' => 99, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'UNIVERSIDAD AUTÓNOMA DE CIUDAD JUÁREZ', 'siglas' => 'UACJ'],
            ['id' => 100, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'TRIBUNAL DE JUSTICIA ADMINISTRATIVA DEL ESTADO DE CHIHUAHUA', 'siglas' => 'TJA'],
            ['id' => 101, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'SECRETARÍA EJECUTIVA DEL SISTEMA ESTATAL ANTICORRUPCIÓN', 'siglas' => 'SESEA'],

            // 102 al 133: JMAS (Asociadas a un municipio específico, ej: nivel municipal = 2, y su respectivo municipio_id)
            ['id' => 102, 'nivel_gobierno_id' => 2, 'municipio_id' => 134, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE AHUMADA', 'siglas' => 'JMAS AHUMADA'],
            ['id' => 103, 'nivel_gobierno_id' => 2, 'municipio_id' => 135, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE ALDAMA', 'siglas' => 'JMAS ALDAMA'],
            ['id' => 104, 'nivel_gobierno_id' => 2, 'municipio_id' => 136, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE ALLENDE', 'siglas' => 'JMAS ALLENDE'],
            ['id' => 105, 'nivel_gobierno_id' => 2, 'municipio_id' => 137, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE AQUILES SERDÁN', 'siglas' => 'JMAS AQUILES SERDÁN'],
            ['id' => 106, 'nivel_gobierno_id' => 2, 'municipio_id' => 138, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE ASCENSIÓN', 'siglas' => 'JMAS ASCENSIÓN'],
            ['id' => 107, 'nivel_gobierno_id' => 2, 'municipio_id' => 140, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE BALLEZA', 'siglas' => 'JMAS BALLEZA'],
            ['id' => 108, 'nivel_gobierno_id' => 2, 'municipio_id' => 142, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE BOCOYNA', 'siglas' => 'JMAS BOCOYNA'],
            ['id' => 109, 'nivel_gobierno_id' => 2, 'municipio_id' => 143, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE BUENAVENTURA', 'siglas' => 'JMAS BUENAVENTURA'],
            ['id' => 110, 'nivel_gobierno_id' => 2, 'municipio_id' => 144, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE CAMARGO', 'siglas' => 'JMAS CAMARGO'],
            ['id' => 111, 'nivel_gobierno_id' => 2, 'municipio_id' => 146, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE CASAS GRANDES', 'siglas' => 'JMAS CASAS GRANDES'],
            ['id' => 112, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE CHIHUAHUA', 'siglas' => 'JMAS CHIHUAHUA'],
            ['id' => 113, 'nivel_gobierno_id' => 2, 'municipio_id' => 148, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE COYAME DEL SOTOL', 'siglas' => 'JMAS COYAME'],
            ['id' => 114, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE CUAUHTÉMOC', 'siglas' => 'JMAS CUAUHTÉMOC'],
            ['id' => 115, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE DELICIAS', 'siglas' => 'JMAS DELICIAS'],
            ['id' => 116, 'nivel_gobierno_id' => 2, 'municipio_id' => 160, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE GUACHOCHI', 'siglas' => 'JMAS GUACHOCHI'],
            ['id' => 117, 'nivel_gobierno_id' => 2, 'municipio_id' => 162, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE GUADALUPE Y CALVO', 'siglas' => 'JMAS GUADALUPE Y CALVO'],
            ['id' => 118, 'nivel_gobierno_id' => 2, 'municipio_id' => 164, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE GUERRERO', 'siglas' => 'JMAS GUERRERO'],
            ['id' => 119, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE HIDALGO DEL PARRAL', 'siglas' => 'JMAS PARRAL'],
            ['id' => 120, 'nivel_gobierno_id' => 2, 'municipio_id' => 169, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE JIMÉNEZ', 'siglas' => 'JMAS JIMÉNEZ'],
            ['id' => 121, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE JUÁREZ', 'siglas' => 'JMAS JUÁREZ'],
            ['id' => 122, 'nivel_gobierno_id' => 2, 'municipio_id' => 173, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE MADERA', 'siglas' => 'JMAS MADERA'],
            ['id' => 123, 'nivel_gobierno_id' => 2, 'municipio_id' => 178, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE MEOQUI', 'siglas' => 'JMAS MEOQUI'],
            ['id' => 124, 'nivel_gobierno_id' => 2, 'municipio_id' => 181, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE NAMIQUIPA', 'siglas' => 'JMAS NAMIQUIPA'],
            ['id' => 125, 'nivel_gobierno_id' => 2, 'municipio_id' => 183, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE NUEVO CASAS GRANDES', 'siglas' => 'JMAS NCG'],
            ['id' => 126, 'nivel_gobierno_id' => 2, 'municipio_id' => 185, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE OJINAGA', 'siglas' => 'JMAS OJINAGA'],
            ['id' => 127, 'nivel_gobierno_id' => 2, 'municipio_id' => 186, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE PRAXEDIS G. GUERRERO', 'siglas' => 'JMAS PRAXEDIS'],
            ['id' => 128, 'nivel_gobierno_id' => 2, 'municipio_id' => 187, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE RIVA PALACIO', 'siglas' => 'JMAS RIVA PALACIO'],
            ['id' => 129, 'nivel_gobierno_id' => 2, 'municipio_id' => 188, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE ROSALES', 'siglas' => 'JMAS ROSALES'],
            ['id' => 130, 'nivel_gobierno_id' => 2, 'municipio_id' => 192, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE SAN FRANCISCO DEL ORO', 'siglas' => 'JMAS STO ORO'],
            ['id' => 131, 'nivel_gobierno_id' => 2, 'municipio_id' => 195, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE SAUCILLO', 'siglas' => 'JMAS SAUCILLO'],
            ['id' => 132, 'nivel_gobierno_id' => 2, 'municipio_id' => 199, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE URUACHI', 'siglas' => 'JMAS URUACHI'],
            ['id' => 133, 'nivel_gobierno_id' => 2, 'municipio_id' => 200, 'nombre' => 'JUNTA MUNICIPAL DE AGUA Y SANEAMIENTO DE VALLE DE ZARAGOZA', 'siglas' => 'JMAS ZARAGOZA'],

            // 134 al 200: Municipios (Cada uno se asocia a sí mismo como municipio)
            ['id' => 134, 'nivel_gobierno_id' => 2, 'municipio_id' => 134, 'nombre' => 'Municipio de Ahumada', 'siglas' => null],
            ['id' => 135, 'nivel_gobierno_id' => 2, 'municipio_id' => 135, 'nombre' => 'Municipio de Aldama', 'siglas' => null],
            ['id' => 136, 'nivel_gobierno_id' => 2, 'municipio_id' => 136, 'nombre' => 'Municipio de Allende', 'siglas' => null],
            ['id' => 137, 'nivel_gobierno_id' => 2, 'municipio_id' => 137, 'nombre' => 'Municipio de Aquiles Serdán', 'siglas' => null],
            ['id' => 138, 'nivel_gobierno_id' => 2, 'municipio_id' => 138, 'nombre' => 'Municipio de Ascensión', 'siglas' => null],
            ['id' => 139, 'nivel_gobierno_id' => 2, 'municipio_id' => 139, 'nombre' => 'Municipio de Bachíniva', 'siglas' => null],
            ['id' => 140, 'nivel_gobierno_id' => 2, 'municipio_id' => 140, 'nombre' => 'Municipio de Balleza', 'siglas' => null],
            ['id' => 141, 'nivel_gobierno_id' => 2, 'municipio_id' => 141, 'nombre' => 'Municipio de Batopilas de Manuel Gómez Morín', 'siglas' => null],
            ['id' => 142, 'nivel_gobierno_id' => 2, 'municipio_id' => 142, 'nombre' => 'Municipio de Bocoyna', 'siglas' => null],
            ['id' => 143, 'nivel_gobierno_id' => 2, 'municipio_id' => 143, 'nombre' => 'Municipio de Buenaventura', 'siglas' => null],
            ['id' => 144, 'nivel_gobierno_id' => 2, 'municipio_id' => 144, 'nombre' => 'Municipio de Camargo', 'siglas' => null],
            ['id' => 145, 'nivel_gobierno_id' => 2, 'municipio_id' => 145, 'nombre' => 'Municipio de Carichí', 'siglas' => null],
            ['id' => 146, 'nivel_gobierno_id' => 2, 'municipio_id' => 146, 'nombre' => 'Municipio de Casas Grandes', 'siglas' => null],
            ['id' => 147, 'nivel_gobierno_id' => 2, 'municipio_id' => 147, 'nombre' => 'Municipio de Coronado', 'siglas' => null],
            ['id' => 148, 'nivel_gobierno_id' => 2, 'municipio_id' => 148, 'nombre' => 'Municipio de Coyame del Sotol', 'siglas' => null],
            ['id' => 149, 'nivel_gobierno_id' => 2, 'municipio_id' => 149, 'nombre' => 'Municipio de La Cruz', 'siglas' => null],
            ['id' => 150, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'Municipio de Cuauhtémoc', 'siglas' => null],
            ['id' => 151, 'nivel_gobierno_id' => 2, 'municipio_id' => 151, 'nombre' => 'Municipio de Cusihuiriachi', 'siglas' => null],
            ['id' => 152, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'Municipio de Chihuahua', 'siglas' => null],
            ['id' => 153, 'nivel_gobierno_id' => 2, 'municipio_id' => 153, 'nombre' => 'Municipio de Chínipas', 'siglas' => null],
            ['id' => 154, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'Municipio de Delicias', 'siglas' => null],
            ['id' => 155, 'nivel_gobierno_id' => 2, 'municipio_id' => 155, 'nombre' => 'Municipio de Dr. Belisario Domínguez', 'siglas' => null],
            ['id' => 156, 'nivel_gobierno_id' => 2, 'municipio_id' => 156, 'nombre' => 'Municipio de Galeana', 'siglas' => null],
            ['id' => 157, 'nivel_gobierno_id' => 2, 'municipio_id' => 157, 'nombre' => 'Municipio de Santa Isabel', 'siglas' => null],
            ['id' => 158, 'nivel_gobierno_id' => 2, 'municipio_id' => 158, 'nombre' => 'Municipio de Gómez Farías', 'siglas' => null],
            ['id' => 159, 'nivel_gobierno_id' => 2, 'municipio_id' => 159, 'nombre' => 'Municipio de Gran Morelos', 'siglas' => null],
            ['id' => 160, 'nivel_gobierno_id' => 2, 'municipio_id' => 160, 'nombre' => 'Municipio de Guachochi', 'siglas' => null],
            ['id' => 161, 'nivel_gobierno_id' => 2, 'municipio_id' => 161, 'nombre' => 'Municipio de Guadalupe', 'siglas' => null],
            ['id' => 162, 'nivel_gobierno_id' => 2, 'municipio_id' => 162, 'nombre' => 'Municipio de Guadalupe y Calvo', 'siglas' => null],
            ['id' => 163, 'nivel_gobierno_id' => 2, 'municipio_id' => 163, 'nombre' => 'Municipio de Guazapares', 'siglas' => null],
            ['id' => 164, 'nivel_gobierno_id' => 2, 'municipio_id' => 164, 'nombre' => 'Municipio de Guerrero', 'siglas' => null],
            ['id' => 165, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'Municipio de Hidalgo del Parral', 'siglas' => null],
            ['id' => 166, 'nivel_gobierno_id' => 2, 'municipio_id' => 166, 'nombre' => 'Municipio de Huejotitán', 'siglas' => null],
            ['id' => 167, 'nivel_gobierno_id' => 2, 'municipio_id' => 167, 'nombre' => 'Municipio de Ignacio Zaragoza', 'siglas' => null],
            ['id' => 168, 'nivel_gobierno_id' => 2, 'municipio_id' => 168, 'nombre' => 'Municipio de Janos', 'siglas' => null],
            ['id' => 169, 'nivel_gobierno_id' => 2, 'municipio_id' => 169, 'nombre' => 'Municipio de Jiménez', 'siglas' => null],
            ['id' => 170, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'Municipio de Juárez', 'siglas' => null],
            ['id' => 171, 'nivel_gobierno_id' => 2, 'municipio_id' => 171, 'nombre' => 'Municipio de Julimes', 'siglas' => null],
            ['id' => 172, 'nivel_gobierno_id' => 2, 'municipio_id' => 172, 'nombre' => 'Municipio de López', 'siglas' => null],
            ['id' => 173, 'nivel_gobierno_id' => 2, 'municipio_id' => 173, 'nombre' => 'Municipio de Madera', 'siglas' => null],
            ['id' => 174, 'nivel_gobierno_id' => 2, 'municipio_id' => 174, 'nombre' => 'Municipio de Maguarichi', 'siglas' => null],
            ['id' => 175, 'nivel_gobierno_id' => 2, 'municipio_id' => 175, 'nombre' => 'Municipio de Manuel Benavides', 'siglas' => null],
            ['id' => 176, 'nivel_gobierno_id' => 2, 'municipio_id' => 176, 'nombre' => 'Municipio de Matachí', 'siglas' => null],
            ['id' => 177, 'nivel_gobierno_id' => 2, 'municipio_id' => 177, 'nombre' => 'Municipio de Matamoros', 'siglas' => null],
            ['id' => 178, 'nivel_gobierno_id' => 2, 'municipio_id' => 178, 'nombre' => 'Municipio de Meoqui', 'siglas' => null],
            ['id' => 179, 'nivel_gobierno_id' => 2, 'municipio_id' => 179, 'nombre' => 'Municipio de Morelos', 'siglas' => null],
            ['id' => 180, 'nivel_gobierno_id' => 2, 'municipio_id' => 180, 'nombre' => 'Municipio de Moris', 'siglas' => null],
            ['id' => 181, 'nivel_gobierno_id' => 2, 'municipio_id' => 181, 'nombre' => 'Municipio de Namiquipa', 'siglas' => null],
            ['id' => 182, 'nivel_gobierno_id' => 2, 'municipio_id' => 182, 'nombre' => 'Municipio de Nonoava', 'siglas' => null],
            ['id' => 183, 'nivel_gobierno_id' => 2, 'municipio_id' => 183, 'nombre' => 'Municipio de Nuevo Casas Grandes', 'siglas' => null],
            ['id' => 184, 'nivel_gobierno_id' => 2, 'municipio_id' => 184, 'nombre' => 'Municipio de Ocampo', 'siglas' => null],
            ['id' => 185, 'nivel_gobierno_id' => 2, 'municipio_id' => 185, 'nombre' => 'Municipio de Ojinaga', 'siglas' => null],
            ['id' => 186, 'nivel_gobierno_id' => 2, 'municipio_id' => 186, 'nombre' => 'Municipio de Praxedis G. Guerrero', 'siglas' => null],
            ['id' => 187, 'nivel_gobierno_id' => 2, 'municipio_id' => 187, 'nombre' => 'Municipio de Riva Palacio', 'siglas' => null],
            ['id' => 188, 'nivel_gobierno_id' => 2, 'municipio_id' => 188, 'nombre' => 'Municipio de Rosales', 'siglas' => null],
            ['id' => 189, 'nivel_gobierno_id' => 2, 'municipio_id' => 189, 'nombre' => 'Municipio de Rosario', 'siglas' => null],
            ['id' => 190, 'nivel_gobierno_id' => 2, 'municipio_id' => 190, 'nombre' => 'Municipio de San Francisco de Borja', 'siglas' => null],
            ['id' => 191, 'nivel_gobierno_id' => 2, 'municipio_id' => 191, 'nombre' => 'Municipio de San Francisco de Conchos', 'siglas' => null],
            ['id' => 192, 'nivel_gobierno_id' => 2, 'municipio_id' => 192, 'nombre' => 'Municipio de San Francisco del Oro', 'siglas' => null],
            ['id' => 193, 'nivel_gobierno_id' => 2, 'municipio_id' => 193, 'nombre' => 'Municipio de Santa Bárbara', 'siglas' => null],
            ['id' => 194, 'nivel_gobierno_id' => 2, 'municipio_id' => 194, 'nombre' => 'Municipio de Satevó', 'siglas' => null],
            ['id' => 195, 'nivel_gobierno_id' => 2, 'municipio_id' => 195, 'nombre' => 'Municipio de Saucillo', 'siglas' => null],
            ['id' => 196, 'nivel_gobierno_id' => 2, 'municipio_id' => 196, 'nombre' => 'Municipio de Temósachic', 'siglas' => null],
            ['id' => 197, 'nivel_gobierno_id' => 2, 'municipio_id' => 197, 'nombre' => 'Municipio de El Tule', 'siglas' => null],
            ['id' => 198, 'nivel_gobierno_id' => 2, 'municipio_id' => 198, 'nombre' => 'Municipio de Urique', 'siglas' => null],
            ['id' => 199, 'nivel_gobierno_id' => 2, 'municipio_id' => 199, 'nombre' => 'Municipio de Uruachi', 'siglas' => null],
            ['id' => 200, 'nivel_gobierno_id' => 2, 'municipio_id' => 200, 'nombre' => 'Municipio de Valle de Zaragoza', 'siglas' => null],

            // 201 al 250: Organismos descentralizados municipales (IMPLAN, DIF, Institutos de la Mujer, etc., vinculados a su municipio respectivo)
            ['id' => 201, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'INSTITUTO MUNICIPAL DE PLANEACIÓN DEL MUNICIPIO DE CHIHUAHUA', 'siglas' => 'IMPLAN CHIHUAHUA'],
            ['id' => 202, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DEL MUNICIPIO DE CHIHUAHUA', 'siglas' => 'IMM CHIHUAHUA'],
            ['id' => 203, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'INSTITUTO MUNICIPAL DE CULTURA FÍSICA Y DEPORTE DEL MUNICIPIO DE CHIHUAHUA', 'siglas' => 'IMCFD CHIHUAHUA'],
            ['id' => 204, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'INSTITUTO DE CULTURA DEL MUNICIPIO DE CHIHUAHUA', 'siglas' => 'ICM CHIHUAHUA'],
            ['id' => 205, 'nivel_gobierno_id' => 2, 'municipio_id' => 152, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CHIHUAHUA', 'siglas' => 'DIF CHIHUAHUA'],
            ['id' => 206, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'INSTITUTO MUNICIPAL DE INVESTIGACIÓN Y PLANEACIÓN DE JUÁREZ', 'siglas' => 'IMIP JUÁREZ'],
            ['id' => 207, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE JUÁREZ', 'siglas' => 'IMM JUÁREZ'],
            ['id' => 208, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'INSTITUTO MUNICIPAL DEL DEPORTE Y CULTURA FÍSICA DE JUÁREZ', 'siglas' => 'IMDEJ JUÁREZ'],
            ['id' => 209, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'INSTITUTO MUNICIPAL DE LA JUVENTUD DE JUÁREZ', 'siglas' => 'IMJUV JUÁREZ'],
            ['id' => 210, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE JUÁREZ', 'siglas' => 'DIF JUÁREZ'],
            ['id' => 211, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'OPERADORA MUNICIPAL DE ESTACIONAMIENTOS DE JUÁREZ', 'siglas' => 'OMEJ JUÁREZ'],
            ['id' => 212, 'nivel_gobierno_id' => 2, 'municipio_id' => 170, 'nombre' => 'SISTEMA DE URBANIZACIÓN MUNICIPAL ADICIONAL DE JUÁREZ', 'siglas' => 'SUMA JUÁREZ'],
            ['id' => 213, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'INSTITUTO MUNICIPAL DE PLANEACIÓN DE CUAUHTÉMOC', 'siglas' => 'IMPLAN CUAUHTÉMOC'],
            ['id' => 214, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE CUAUHTÉMOC', 'siglas' => 'IMM CUAUHTÉMOC'],
            ['id' => 215, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CUAUHTÉMOC', 'siglas' => 'DIF CUAUHTÉMOC'],
            ['id' => 216, 'nivel_gobierno_id' => 2, 'municipio_id' => 150, 'nombre' => 'INSTITUTO MUNICIPAL DE CULTURA FÍSICA Y DEPORTE DE CUAUHTÉMOC', 'siglas' => 'IMCFD CUAUHTÉMOC'],
            ['id' => 217, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'INSTITUTO MUNICIPAL DE PLANEACIÓN DE DELICIAS', 'siglas' => 'IMPLAN DELICIAS'],
            ['id' => 218, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE DELICIAS', 'siglas' => 'IMM DELICIAS'],
            ['id' => 219, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE DELICIAS', 'siglas' => 'DIF DELICIAS'],
            ['id' => 220, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'INSTITUTO MUNICIPAL DEL DEPORTE Y LA JUVENTUD DE DELICIAS', 'siglas' => 'INMUDEJ DELICIAS'],
            ['id' => 221, 'nivel_gobierno_id' => 2, 'municipio_id' => 154, 'nombre' => 'CONSEJO DE DESARROLLO ECONÓMICO REGIONAL DE DELICIAS', 'siglas' => 'CODER DELICIAS'],
            ['id' => 222, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'INSTITUTO MUNICIPAL DE LA JUVENTUD DE HIDALGO DEL PARRAL', 'siglas' => 'IMJUV PARRAL'],
            ['id' => 223, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE HIDALGO DEL PARRAL', 'siglas' => 'IMM PARRAL'],
            ['id' => 224, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE HIDALGO DEL PARRAL', 'siglas' => 'DIF PARRAL'],
            ['id' => 225, 'nivel_gobierno_id' => 2, 'municipio_id' => 165, 'nombre' => 'INSTITUTO MUNICIPAL DE DEPORTE DE HIDALGO DEL PARRAL', 'siglas' => 'INMUDEPA PARRAL'],
            ['id' => 226, 'nivel_gobierno_id' => 2, 'municipio_id' => 144, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CAMARGO', 'siglas' => 'DIF CAMARGO'],
            ['id' => 227, 'nivel_gobierno_id' => 2, 'municipio_id' => 144, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE CAMARGO', 'siglas' => 'IMM CAMARGO'],
            ['id' => 228, 'nivel_gobierno_id' => 2, 'municipio_id' => 183, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE NUEVO CASAS GRANDES', 'siglas' => 'DIF NCG'],
            ['id' => 229, 'nivel_gobierno_id' => 2, 'municipio_id' => 183, 'nombre' => 'INSTITUTO MUNICIPAL DE LAS MUJERES DE NUEVO CASAS GRANDES', 'siglas' => 'IMM NCG'],
            ['id' => 230, 'nivel_gobierno_id' => 2, 'municipio_id' => 169, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE JIMÉNEZ', 'siglas' => 'DIF JIMÉNEZ'],
            ['id' => 231, 'nivel_gobierno_id' => 2, 'municipio_id' => 185, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE OJINAGA', 'siglas' => 'DIF OJINAGA'],
            ['id' => 232, 'nivel_gobierno_id' => 2, 'municipio_id' => 164, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE GUERRERO', 'siglas' => 'DIF GUERRERO'],
            ['id' => 233, 'nivel_gobierno_id' => 2, 'municipio_id' => 142, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE BOCOYNA', 'siglas' => 'DIF BOCOYNA'],
            ['id' => 234, 'nivel_gobierno_id' => 2, 'municipio_id' => 160, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE GUACHOCHI', 'siglas' => 'DIF GUACHOCHI'],
            ['id' => 235, 'nivel_gobierno_id' => 2, 'municipio_id' => 195, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE SAUCILLO', 'siglas' => 'DIF SAUCILLO'],
            ['id' => 236, 'nivel_gobierno_id' => 2, 'municipio_id' => 178, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE MEOQUI', 'siglas' => 'DIF MEOQUI'],
            ['id' => 237, 'nivel_gobierno_id' => 2, 'municipio_id' => 138, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE ASCENSIÓN', 'siglas' => 'DIF ASCENSIÓN'],
            ['id' => 238, 'nivel_gobierno_id' => 2, 'municipio_id' => 143, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE BUENAVENTURA', 'siglas' => 'DIF BUENAVENTURA'],
            ['id' => 239, 'nivel_gobierno_id' => 2, 'municipio_id' => 173, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE MADERA', 'siglas' => 'DIF MADERA'],
            ['id' => 240, 'nivel_gobierno_id' => 2, 'municipio_id' => 162, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE GUADALUPE Y CALVO', 'siglas' => 'DIF GUADALUPE Y CALVO'],
            ['id' => 241, 'nivel_gobierno_id' => 2, 'municipio_id' => 146, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CASAS GRANDES', 'siglas' => 'DIF CASAS GRANDES'],
            ['id' => 242, 'nivel_gobierno_id' => 2, 'municipio_id' => 181, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE NAMIQUIPA', 'siglas' => 'DIF NAMIQUIPA'],
            ['id' => 243, 'nivel_gobierno_id' => 2, 'municipio_id' => 135, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE ALDAMA', 'siglas' => 'DIF ALDAMA'],
            ['id' => 244, 'nivel_gobierno_id' => 2, 'municipio_id' => 141, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE BATOPILAS', 'siglas' => 'DIF BATOPILAS'],
            ['id' => 245, 'nivel_gobierno_id' => 2, 'municipio_id' => 145, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CARICHÍ', 'siglas' => 'DIF CARICHÍ'],
            ['id' => 246, 'nivel_gobierno_id' => 2, 'municipio_id' => 153, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CHÍNIPAS', 'siglas' => 'DIF CHÍNIPAS'],
            ['id' => 247, 'nivel_gobierno_id' => 2, 'municipio_id' => 151, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE CUSIHUIRIACHI', 'siglas' => 'DIF CUSIHUIRIACHI'],
            ['id' => 248, 'nivel_gobierno_id' => 2, 'municipio_id' => 156, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE GALEANA', 'siglas' => 'DIF GALEANA'],
            ['id' => 249, 'nivel_gobierno_id' => 2, 'municipio_id' => 159, 'nombre' => 'DESARROLLO INTEGRAL DE LA FAMILIA DEL MUNICIPIO DE GRAN MORELOS', 'siglas' => 'DIF GRAN MORELOS'],
            ['id' => 250, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FOMENTO Y DESARROLLO ARTESANAL DEL ESTADO DE CHIHUAHUA', 'siglas' => 'FODARCH'],
            ['id' => 251, 'nivel_gobierno_id' => 1, 'municipio_id' => null, 'nombre' => 'FISCALÍA ANTICORRUPCIÓN DEL ESTADO DE CHIHUAHUA', 'siglas' => 'FACH'],
        ];

        DB::table('entes')->insert($entes);
    }
}