<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnteSeeder extends Seeder
{
    public function run(): void
    {
        $entes = [
            ['id' => 1, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Despacho del Ejecutivo', 'siglas' => null, 'activo' => true],
            ['id' => 2, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría General de Gobierno', 'siglas' => null, 'activo' => true],
            ['id' => 3, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Hacienda', 'siglas' => null, 'activo' => true],
            ['id' => 4, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Innovación y Desarrollo Económico', 'siglas' => null, 'activo' => true],
            ['id' => 5, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría Desarrollo Humano y Bien Común', 'siglas' => null, 'activo' => true],
            ['id' => 6, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Salud', 'siglas' => null, 'activo' => true],
            ['id' => 7, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Educación y Deporte', 'siglas' => null, 'activo' => true],
            ['id' => 8, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Trabajo y Previsión Social', 'siglas' => null, 'activo' => true],
            ['id' => 9, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Cultura', 'siglas' => null, 'activo' => true],
            ['id' => 10, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Comunicaciones y Obras Públicas', 'siglas' => null, 'activo' => true],
            ['id' => 11, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Desarrollo Urbano y Ecología', 'siglas' => null, 'activo' => true],
            ['id' => 12, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Desarrollo Rural', 'siglas' => null, 'activo' => true],
            ['id' => 13, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Desarrollo Municipal', 'siglas' => null, 'activo' => true],
            ['id' => 14, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de la Función Pública', 'siglas' => null, 'activo' => true],
            ['id' => 15, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fiscalía General del Estado', 'siglas' => null, 'activo' => true],
            ['id' => 16, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Consejería Jurídica', 'siglas' => null, 'activo' => true],
            ['id' => 17, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Coordinación de Comunicación', 'siglas' => null, 'activo' => true],
            ['id' => 18, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Coordinación de Relaciones Públicas', 'siglas' => null, 'activo' => true],
            ['id' => 19, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Representación del Gobierno del Estado en la Cd. de México', 'siglas' => null, 'activo' => true],
            ['id' => 20, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Coordinación de Asesores y Proyectos Especiales', 'siglas' => null, 'activo' => true],
            ['id' => 21, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Coordinación Ejecutiva de Gabinete', 'siglas' => null, 'activo' => true],
            ['id' => 22, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de pueblos y comunidades indígenas', 'siglas' => null, 'activo' => true],
            ['id' => 23, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Coordinación de Política Digital', 'siglas' => null, 'activo' => true],
            ['id' => 24, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Servicios Educativos del Estado de Chihuahua', 'siglas' => 'SEECH', 'activo' => true],
            ['id' => 25, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnológica de Chihuahua', 'siglas' => 'UTCH', 'activo' => true],
            ['id' => 26, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnológica de Ciudad Juárez', 'siglas' => 'UTCJ', 'activo' => true],
            ['id' => 27, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Colegio de Bachilleres del Estado de Chihuahua', 'siglas' => 'COBACH', 'activo' => true],
            ['id' => 28, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Tecnológico Superior de Nuevo Casas Grandes', 'siglas' => 'ITSNCG', 'activo' => true],
            ['id' => 29, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Colegio de Estudios Cientificos y Tecnologicos del Estado de Chihuahua', 'siglas' => 'CECYTECH', 'activo' => true],
            ['id' => 30, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Colegio de Educación Profesional Técnica del Estado de Chihuahua', 'siglas' => 'CONALEP', 'activo' => true],
            ['id' => 31, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de Educacion para los Adultos', 'siglas' => 'ICHEA', 'activo' => true],
            ['id' => 32, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto de Apoyo al Desarrollo Tecnologico', 'siglas' => 'INADET', 'activo' => true],
            ['id' => 33, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto de Capacitacion para el Trabajo del Estado de Chihuahua', 'siglas' => 'ICATECH', 'activo' => true],
            ['id' => 34, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fomento y Desarrollo Artesanal del Estado de Chihuahua', 'siglas' => 'FODARCH', 'activo' => true],
            ['id' => 35, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Servicios de Salud de Chihuahua', 'siglas' => 'SSCH', 'activo' => true],
            ['id' => 36, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de Salud', 'siglas' => 'ICHISAL', 'activo' => true],
            ['id' => 37, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Desarrollo Integral de la Familia del Estado de Chihuahua', 'siglas' => 'DIF', 'activo' => true],
            ['id' => 38, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de Las Mujeres', 'siglas' => 'ICHIMU', 'activo' => true],
            ['id' => 39, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Consejo Estatal de Población', 'siglas' => 'COESPO', 'activo' => true],
            ['id' => 40, 'nivel_gobierno_id' => 2, 'municipio_id' => 35, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Cd. Hidalgo del Parral', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 41, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Promotora para el Desarrollo Económico de Chihuahua', 'siglas' => 'PRODECH', 'activo' => true],
            ['id' => 42, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Pensiones Civiles del Estado de Chihuahua', 'siglas' => 'PCE', 'activo' => true],
            ['id' => 43, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Junta Central de Agua y Saneamiento', 'siglas' => 'JCAS', 'activo' => true],
            ['id' => 44, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Escuela Normal Superior Prof. José E. Medrano R.', 'siglas' => 'ENSECH', 'activo' => true],
            ['id' => 45, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense del Deporte y Cultura Fisica', 'siglas' => 'ICHD', 'activo' => true],
            ['id' => 46, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de la Juventud', 'siglas' => 'ICHIJUV', 'activo' => true],
            ['id' => 47, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Junta de Asistencia Social Privada del Estado de Chihuahua', 'siglas' => 'JASP', 'activo' => true],
            ['id' => 48, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'El Colegio de Chihuahua', 'siglas' => 'COLECH', 'activo' => true],
            ['id' => 49, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto de Innovacion y Competitividad', 'siglas' => 'I2C', 'activo' => true],
            ['id' => 50, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de Infraestructura Fisica Educativa', 'siglas' => 'ICHIFE', 'activo' => true],
            ['id' => 51, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Politecnica de Chihuahua', 'siglas' => 'UPCH', 'activo' => true],
            ['id' => 52, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnológica de la Tarahumara', 'siglas' => 'UTT', 'activo' => true],
            ['id' => 53, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnologica de Parral', 'siglas' => 'UTP', 'activo' => true],
            ['id' => 54, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Pedagogica Nacional del Estado de Chihuahua', 'siglas' => 'UPNECH', 'activo' => true],
            ['id' => 55, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnologica de la Babicora', 'siglas' => 'UTB', 'activo' => true],
            ['id' => 56, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Comision Estatal de Vivienda Suelo E Infraestructura de Chihuahua', 'siglas' => 'COESVI', 'activo' => true],
            ['id' => 57, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnológica de Paquime', 'siglas' => 'UTP', 'activo' => true],
            ['id' => 58, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnológica de Camargo', 'siglas' => 'UTC', 'activo' => true],
            ['id' => 59, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnologica de Chihuahua Sur', 'siglas' => 'UTCH SUR', 'activo' => true],
            ['id' => 60, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Subsistema de Preparatoria Abierta y Telebachillerato del Estado de Chihuahua', 'siglas' => 'SPAT', 'activo' => true],
            ['id' => 61, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Tecnologica Paso del Norte', 'siglas' => 'UTPN', 'activo' => true],
            ['id' => 62, 'nivel_gobierno_id' => 2, 'municipio_id' => 19, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Cd. Chihuahua', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 63, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Regimen Estatal de Proteccion Social en Salud', 'siglas' => 'REPSS', 'activo' => true],
            ['id' => 64, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría Ejecutiva del Sistema Estatal Anticorrupción', 'siglas' => 'SESEA', 'activo' => true],
            ['id' => 65, 'nivel_gobierno_id' => 2, 'municipio_id' => 3, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Valle de Allende', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 66, 'nivel_gobierno_id' => 2, 'municipio_id' => 5, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Ascencion', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 67, 'nivel_gobierno_id' => 2, 'municipio_id' => 7, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Balleza', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 68, 'nivel_gobierno_id' => 2, 'municipio_id' => 27, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Guachochi', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 69, 'nivel_gobierno_id' => 2, 'municipio_id' => 36, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Jimenez', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 70, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fibra Estatal de Chihuahua', 'siglas' => 'FEC', 'activo' => true],
            ['id' => 71, 'nivel_gobierno_id' => 2, 'municipio_id' => 45, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Meoqui', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 72, 'nivel_gobierno_id' => 2, 'municipio_id' => 60, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Santa Barbara', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 73, 'nivel_gobierno_id' => 2, 'municipio_id' => 39, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Villa Lopez', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 74, 'nivel_gobierno_id' => 2, 'municipio_id' => 52, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Ojinaga', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 75, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Junta Rural de Agua Potable de Col. Hidalgo', 'siglas' => 'JRAP', 'activo' => true],
            ['id' => 76, 'nivel_gobierno_id' => 2, 'municipio_id' => 37, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Juarez', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 77, 'nivel_gobierno_id' => 2, 'municipio_id' => 13, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Casas Grandes', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 78, 'nivel_gobierno_id' => 2, 'municipio_id' => 17, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Cuauhtémoc', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 79, 'nivel_gobierno_id' => 2, 'municipio_id' => 26, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Gran Morelos', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 80, 'nivel_gobierno_id' => 2, 'municipio_id' => 31, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Guerrero', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 81, 'nivel_gobierno_id' => 2, 'municipio_id' => 34, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Ignacio Zaragoza', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 82, 'nivel_gobierno_id' => 2, 'municipio_id' => 40, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Madera', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 83, 'nivel_gobierno_id' => 2, 'municipio_id' => 44, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Matamoros', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 84, 'nivel_gobierno_id' => 2, 'municipio_id' => 55, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Rosales', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 85, 'nivel_gobierno_id' => 2, 'municipio_id' => 59, 'nombre' => 'Junta Municipal de Agua y Saneamiento de San Francisco del Oro', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 86, 'nivel_gobierno_id' => 2, 'municipio_id' => 62, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Saucillo', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 87, 'nivel_gobierno_id' => 2, 'municipio_id' => 24, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Santa Isabel', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 88, 'nivel_gobierno_id' => 2, 'municipio_id' => 17, 'nombre' => 'Junta Rural de Agua y Saneamiento de Álvaro Obregón', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 89, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Junta Rural de Agua Potable de Benito Juárez', 'siglas' => 'JRAP', 'activo' => true],
            ['id' => 90, 'nivel_gobierno_id' => 2, 'municipio_id' => 55, 'nombre' => 'Junta Rural de Agua y Saneamiento de Congregacion Ortiz', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 91, 'nivel_gobierno_id' => 2, 'municipio_id' => 9, 'nombre' => 'Junta Rural de Agua y Saneamiento de Creel', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 92, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Junta Rural de Agua y Saneamiento del Ejido Constitución', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 93, 'nivel_gobierno_id' => 2, 'municipio_id' => 53, 'nombre' => 'Junta Rural de Agua Potable de El Porvenir', 'siglas' => 'JRAP', 'activo' => true],
            ['id' => 94, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Promotora de Símbolos', 'siglas' => null, 'activo' => true],
            ['id' => 95, 'nivel_gobierno_id' => 2, 'municipio_id' => 31, 'nombre' => 'Junta Rural de Agua y Saneamiento de El Terrero', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 96, 'nivel_gobierno_id' => 2, 'municipio_id' => 28, 'nombre' => 'Junta Rural de Agua y Saneamiento de Guadalupe D.B.', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 97, 'nivel_gobierno_id' => 2, 'municipio_id' => 45, 'nombre' => 'Junta Rural de Agua y Saneamiento de Lázaro Cárdenas', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 98, 'nivel_gobierno_id' => 2, 'municipio_id' => 39, 'nombre' => 'Junta Rural de Agua y Saneamiento de López Mateos', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 99, 'nivel_gobierno_id' => 2, 'municipio_id' => 62, 'nombre' => 'Junta Rural de Agua y Saneamiento de Naica', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 100, 'nivel_gobierno_id' => 2, 'municipio_id' => 53, 'nombre' => 'Junta Rural de Agua y Saneamiento de Porfirio Parra', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 101, 'nivel_gobierno_id' => 2, 'municipio_id' => 10, 'nombre' => 'Junta Rural de Agua y Saneamiento de Flores Magón', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 102, 'nivel_gobierno_id' => 2, 'municipio_id' => 3, 'nombre' => 'Junta Rural de Agua y Saneamiento del Pueblito de Allende', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 103, 'nivel_gobierno_id' => 2, 'municipio_id' => 53, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Práxedis G. Guerrero', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 104, 'nivel_gobierno_id' => 2, 'municipio_id' => 5, 'nombre' => 'Junta Rural de Agua y Saneamiento de Puerto Palomas', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 105, 'nivel_gobierno_id' => 2, 'municipio_id' => 9, 'nombre' => 'Junta Rural de Agua y Saneamiento de San Juanito', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 106, 'nivel_gobierno_id' => 2, 'municipio_id' => 10, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Buenaventura', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 107, 'nivel_gobierno_id' => 2, 'municipio_id' => 17, 'nombre' => 'Junta Rural de Agua y Saneamiento de Anáhuac', 'siglas' => 'JRAS', 'activo' => true],
            ['id' => 108, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Comisión Estatal para la Protección Contra Riesgos Sanitarios', 'siglas' => 'COESPRIS', 'activo' => true],
            ['id' => 109, 'nivel_gobierno_id' => 2, 'municipio_id' => 4, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Aquiles Serdan', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 110, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Comisión Ejecutiva de Atención a Victimas', 'siglas' => 'CEAVE', 'activo' => true],
            ['id' => 111, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideapech', 'siglas' => 'FIDEAPECH', 'activo' => true],
            ['id' => 112, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Programa Escuelas de Calidad', 'siglas' => 'PEC', 'activo' => true],
            ['id' => 113, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Casa Chihuahua Centro de Patrimonio Cultural', 'siglas' => null, 'activo' => true],
            ['id' => 114, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Policia Amigo', 'siglas' => null, 'activo' => true],
            ['id' => 115, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Transito Amigo', 'siglas' => null, 'activo' => true],
            ['id' => 116, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Expo-Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 117, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Barrancas del Cobre', 'siglas' => null, 'activo' => true],
            ['id' => 118, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo de Fomento Agropecuario del Estado de Chihuahua', 'siglas' => 'FOFAE', 'activo' => true],
            ['id' => 119, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo Mixto Conacyt - Gobierno del Estado de Chihuahua', 'siglas' => 'FOMIX', 'activo' => true],
            ['id' => 120, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso del Programa de Carreteras Federales y Estatales de Cuota', 'siglas' => null, 'activo' => true],
            ['id' => 121, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo de Apoyo a los Usuarios de Riego Por Bombeo Electrico del Estado de Chihuahua', 'siglas' => 'FURBE', 'activo' => true],
            ['id' => 123, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondoestatal de Apoyo a la Comercializacion del Frijol', 'siglas' => 'FEAFRICH', 'activo' => true],
            ['id' => 124, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso para el Desarrollo Forestal Sustentable en el Estado', 'siglas' => 'FIDEFOSE', 'activo' => true],
            ['id' => 125, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo de Atención para Niños y Niñas Hijos de las Víctimas de la Lucha Contra el Crimen', 'siglas' => 'FANVI', 'activo' => true],
            ['id' => 126, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso de Puentes Fronterizos', 'siglas' => 'FPFCH', 'activo' => true],
            ['id' => 127, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso Avalos', 'siglas' => null, 'activo' => true],
            ['id' => 128, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo Estatal de Proteccion al Ambiente del Estado de Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 129, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso de Transporte Autosustentable Vivebus Cd. Juarez', 'siglas' => null, 'activo' => true],
            ['id' => 130, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Chihuahua Buro de Convenciones A.C.', 'siglas' => null, 'activo' => true],
            ['id' => 131, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretariado Ejecutivo del Sistema Estatal de Seguridad Pública', 'siglas' => 'SESESP', 'activo' => true],
            ['id' => 132, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Administradora de Servicios Aeroportuarios de Chihuahua S.A. de C.V.', 'siglas' => null, 'activo' => true],
            ['id' => 133, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Operadora de Transporte Vivebus Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 134, 'nivel_gobierno_id' => 3, 'municipio_id' => 1, 'nombre' => 'Municipio de Ahumada', 'siglas' => null, 'activo' => true],
            ['id' => 135, 'nivel_gobierno_id' => 3, 'municipio_id' => 2, 'nombre' => 'Municipio de Aldama', 'siglas' => null, 'activo' => true],
            ['id' => 136, 'nivel_gobierno_id' => 3, 'municipio_id' => 3, 'nombre' => 'Municipio de Allende', 'siglas' => null, 'activo' => true],
            ['id' => 137, 'nivel_gobierno_id' => 3, 'municipio_id' => 4, 'nombre' => 'Municipio de Aquiles Serdán', 'siglas' => null, 'activo' => true],
            ['id' => 138, 'nivel_gobierno_id' => 3, 'municipio_id' => 5, 'nombre' => 'Municipio de Ascensión', 'siglas' => null, 'activo' => true],
            ['id' => 139, 'nivel_gobierno_id' => 3, 'municipio_id' => 6, 'nombre' => 'Municipio de Bachíniva', 'siglas' => null, 'activo' => true],
            ['id' => 140, 'nivel_gobierno_id' => 3, 'municipio_id' => 7, 'nombre' => 'Municipio de Balleza', 'siglas' => null, 'activo' => true],
            ['id' => 141, 'nivel_gobierno_id' => 3, 'municipio_id' => 8, 'nombre' => 'Municipio de Batopilas de Manuel Gómez Morín', 'siglas' => null, 'activo' => true],
            ['id' => 142, 'nivel_gobierno_id' => 3, 'municipio_id' => 9, 'nombre' => 'Municipio de Bocoyna', 'siglas' => null, 'activo' => true],
            ['id' => 143, 'nivel_gobierno_id' => 3, 'municipio_id' => 10, 'nombre' => 'Municipio de Buenaventura', 'siglas' => null, 'activo' => true],
            ['id' => 144, 'nivel_gobierno_id' => 3, 'municipio_id' => 11, 'nombre' => 'Municipio de Camargo', 'siglas' => null, 'activo' => true],
            ['id' => 145, 'nivel_gobierno_id' => 3, 'municipio_id' => 12, 'nombre' => 'Municipio de Carichí', 'siglas' => null, 'activo' => true],
            ['id' => 146, 'nivel_gobierno_id' => 3, 'municipio_id' => 13, 'nombre' => 'Municipio de Casas Grandes', 'siglas' => null, 'activo' => true],
            ['id' => 147, 'nivel_gobierno_id' => 3, 'municipio_id' => 14, 'nombre' => 'Municipio de Coronado', 'siglas' => null, 'activo' => true],
            ['id' => 148, 'nivel_gobierno_id' => 3, 'municipio_id' => 15, 'nombre' => 'Municipio de Coyame del Sotol', 'siglas' => null, 'activo' => true],
            ['id' => 149, 'nivel_gobierno_id' => 3, 'municipio_id' => 16, 'nombre' => 'Municipio de La Cruz', 'siglas' => null, 'activo' => true],
            ['id' => 150, 'nivel_gobierno_id' => 3, 'municipio_id' => 17, 'nombre' => 'Municipio de Cuauhtémoc', 'siglas' => null, 'activo' => true],
            ['id' => 151, 'nivel_gobierno_id' => 3, 'municipio_id' => 18, 'nombre' => 'Municipio de Cusihuiriachi', 'siglas' => null, 'activo' => true],
            ['id' => 152, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 153, 'nivel_gobierno_id' => 3, 'municipio_id' => 20, 'nombre' => 'Municipio de Chínipas', 'siglas' => null, 'activo' => true],
            ['id' => 154, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias', 'siglas' => null, 'activo' => true],
            ['id' => 155, 'nivel_gobierno_id' => 3, 'municipio_id' => 22, 'nombre' => 'Municipio de Dr. Belisario Domínguez', 'siglas' => null, 'activo' => true],
            ['id' => 156, 'nivel_gobierno_id' => 3, 'municipio_id' => 23, 'nombre' => 'Municipio de Galeana', 'siglas' => null, 'activo' => true],
            ['id' => 157, 'nivel_gobierno_id' => 3, 'municipio_id' => 24, 'nombre' => 'Municipio de Santa Isabel', 'siglas' => null, 'activo' => true],
            ['id' => 158, 'nivel_gobierno_id' => 3, 'municipio_id' => 25, 'nombre' => 'Municipio de Gómez Farías', 'siglas' => null, 'activo' => true],
            ['id' => 159, 'nivel_gobierno_id' => 3, 'municipio_id' => 26, 'nombre' => 'Municipio de Gran Morelos', 'siglas' => null, 'activo' => true],
            ['id' => 160, 'nivel_gobierno_id' => 3, 'municipio_id' => 27, 'nombre' => 'Municipio de Guachochi', 'siglas' => null, 'activo' => true],
            ['id' => 161, 'nivel_gobierno_id' => 3, 'municipio_id' => 28, 'nombre' => 'Municipio de Guadalupe', 'siglas' => null, 'activo' => true],
            ['id' => 162, 'nivel_gobierno_id' => 3, 'municipio_id' => 29, 'nombre' => 'Municipio de Guadalupe y Calvo', 'siglas' => null, 'activo' => true],
            ['id' => 163, 'nivel_gobierno_id' => 3, 'municipio_id' => 30, 'nombre' => 'Municipio de Guazapares', 'siglas' => null, 'activo' => true],
            ['id' => 164, 'nivel_gobierno_id' => 3, 'municipio_id' => 31, 'nombre' => 'Municipio de Guerrero', 'siglas' => null, 'activo' => true],
            ['id' => 165, 'nivel_gobierno_id' => 3, 'municipio_id' => 35, 'nombre' => 'Municipio de Hidalgo del Parral', 'siglas' => null, 'activo' => true],
            ['id' => 166, 'nivel_gobierno_id' => 3, 'municipio_id' => 33, 'nombre' => 'Municipio de Huejotitán', 'siglas' => null, 'activo' => true],
            ['id' => 167, 'nivel_gobierno_id' => 3, 'municipio_id' => 34, 'nombre' => 'Municipio de Ignacio Zaragoza', 'siglas' => null, 'activo' => true],
            ['id' => 168, 'nivel_gobierno_id' => 3, 'municipio_id' => 35, 'nombre' => 'Municipio de Janos', 'siglas' => null, 'activo' => true],
            ['id' => 169, 'nivel_gobierno_id' => 3, 'municipio_id' => 36, 'nombre' => 'Municipio de Jiménez', 'siglas' => null, 'activo' => true],
            ['id' => 170, 'nivel_gobierno_id' => 3, 'municipio_id' => 37, 'nombre' => 'Municipio de Juárez', 'siglas' => null, 'activo' => true],
            ['id' => 171, 'nivel_gobierno_id' => 3, 'municipio_id' => 38, 'nombre' => 'Municipio de Julimes', 'siglas' => null, 'activo' => true],
            ['id' => 172, 'nivel_gobierno_id' => 3, 'municipio_id' => 39, 'nombre' => 'Municipio de López', 'siglas' => null, 'activo' => true],
            ['id' => 173, 'nivel_gobierno_id' => 3, 'municipio_id' => 40, 'nombre' => 'Municipio de Madera', 'siglas' => null, 'activo' => true],
            ['id' => 174, 'nivel_gobierno_id' => 3, 'municipio_id' => 41, 'nombre' => 'Municipio de Maguarichi', 'siglas' => null, 'activo' => true],
            ['id' => 175, 'nivel_gobierno_id' => 3, 'municipio_id' => 42, 'nombre' => 'Municipio de Manuel Benavides', 'siglas' => null, 'activo' => true],
            ['id' => 176, 'nivel_gobierno_id' => 3, 'municipio_id' => 43, 'nombre' => 'Municipio de Matachí', 'siglas' => null, 'activo' => true],
            ['id' => 177, 'nivel_gobierno_id' => 3, 'municipio_id' => 44, 'nombre' => 'Municipio de Matamoros', 'siglas' => null, 'activo' => true],
            ['id' => 178, 'nivel_gobierno_id' => 3, 'municipio_id' => 45, 'nombre' => 'Municipio de Meoqui', 'siglas' => null, 'activo' => true],
            ['id' => 179, 'nivel_gobierno_id' => 3, 'municipio_id' => 46, 'nombre' => 'Municipio de Morelos', 'siglas' => null, 'activo' => true],
            ['id' => 180, 'nivel_gobierno_id' => 3, 'municipio_id' => 47, 'nombre' => 'Municipio de Moris', 'siglas' => null, 'activo' => true],
            ['id' => 181, 'nivel_gobierno_id' => 3, 'municipio_id' => 48, 'nombre' => 'Municipio de Namiquipa', 'siglas' => null, 'activo' => true],
            ['id' => 182, 'nivel_gobierno_id' => 3, 'municipio_id' => 49, 'nombre' => 'Municipio de Nonoava', 'siglas' => null, 'activo' => true],
            ['id' => 183, 'nivel_gobierno_id' => 3, 'municipio_id' => 50, 'nombre' => 'Municipio de Nuevo Casas Grandes', 'siglas' => null, 'activo' => true],
            ['id' => 184, 'nivel_gobierno_id' => 3, 'municipio_id' => 51, 'nombre' => 'Municipio de Ocampo', 'siglas' => null, 'activo' => true],
            ['id' => 185, 'nivel_gobierno_id' => 3, 'municipio_id' => 52, 'nombre' => 'Municipio de Ojinaga', 'siglas' => null, 'activo' => true],
            ['id' => 186, 'nivel_gobierno_id' => 3, 'municipio_id' => 53, 'nombre' => 'Municipio de Praxedis G. Guerrero', 'siglas' => null, 'activo' => true],
            ['id' => 187, 'nivel_gobierno_id' => 3, 'municipio_id' => 54, 'nombre' => 'Municipio de Riva Palacio', 'siglas' => null, 'activo' => true],
            ['id' => 188, 'nivel_gobierno_id' => 3, 'municipio_id' => 55, 'nombre' => 'Municipio de Rosales', 'siglas' => null, 'activo' => true],
            ['id' => 189, 'nivel_gobierno_id' => 3, 'municipio_id' => 56, 'nombre' => 'Municipio de Rosario', 'siglas' => null, 'activo' => true],
            ['id' => 190, 'nivel_gobierno_id' => 3, 'municipio_id' => 57, 'nombre' => 'Municipio de San Francisco de Borja', 'siglas' => null, 'activo' => true],
            ['id' => 191, 'nivel_gobierno_id' => 3, 'municipio_id' => 58, 'nombre' => 'Municipio de San Francisco de Conchos', 'siglas' => null, 'activo' => true],
            ['id' => 192, 'nivel_gobierno_id' => 3, 'municipio_id' => 59, 'nombre' => 'Municipio de San Francisco del Oro', 'siglas' => null, 'activo' => true],
            ['id' => 193, 'nivel_gobierno_id' => 3, 'municipio_id' => 60, 'nombre' => 'Municipio de Santa Bárbara', 'siglas' => null, 'activo' => true],
            ['id' => 194, 'nivel_gobierno_id' => 3, 'municipio_id' => 61, 'nombre' => 'Municipio de Satevó', 'siglas' => null, 'activo' => true],
            ['id' => 195, 'nivel_gobierno_id' => 3, 'municipio_id' => 62, 'nombre' => 'Municipio de Saucillo', 'siglas' => null, 'activo' => true],
            ['id' => 196, 'nivel_gobierno_id' => 3, 'municipio_id' => 63, 'nombre' => 'Municipio de Temósachic', 'siglas' => null, 'activo' => true],
            ['id' => 197, 'nivel_gobierno_id' => 3, 'municipio_id' => 64, 'nombre' => 'Municipio de El Tule', 'siglas' => null, 'activo' => true],
            ['id' => 198, 'nivel_gobierno_id' => 3, 'municipio_id' => 65, 'nombre' => 'Municipio de Urique', 'siglas' => null, 'activo' => true],
            ['id' => 199, 'nivel_gobierno_id' => 3, 'municipio_id' => 66, 'nombre' => 'Municipio de Uruachi', 'siglas' => null, 'activo' => true],
            ['id' => 200, 'nivel_gobierno_id' => 3, 'municipio_id' => 67, 'nombre' => 'Municipio de Valle de Zaragoza', 'siglas' => null, 'activo' => true],
            ['id' => 261, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fiscalía Anticorrupción del Estado de Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 262, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Instituto de la cultura', 'siglas' => null, 'activo' => true],
            ['id' => 263, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de seguridad', 'siglas' => null, 'activo' => true],
            ['id' => 264, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Secretaría de Seguridad Pública del Estado de Chihuahua', 'siglas' => 'SSPE', 'activo' => true],
            ['id' => 265, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Auditoría Superior del Estado de Chihuahua', 'siglas' => 'ASE', 'activo' => true],
            ['id' => 266, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Instituto Municipal de Pensiones', 'siglas' => 'IMPE', 'activo' => true],
            ['id' => 267, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de Desarrollo Económico y Turístico', 'siglas' => null, 'activo' => true],
            ['id' => 268, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - DIF', 'siglas' => 'DIF', 'activo' => true],
            ['id' => 269, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Instituto Municipal de la Cultura Física y el Deporte', 'siglas' => 'IMCFD', 'activo' => true],
            ['id' => 270, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de Desarrollo Rural', 'siglas' => null, 'activo' => true],
            ['id' => 271, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de Desarrollo Urbano y Ecología', 'siglas' => null, 'activo' => true],
            ['id' => 272, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de Servicios Públicos Municipales', 'siglas' => null, 'activo' => true],
            ['id' => 273, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Consejo de Urbanización Municipal', 'siglas' => 'CUM', 'activo' => true],
            ['id' => 274, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Comisión Estatal de los Derechos Humanos', 'siglas' => 'CEDH', 'activo' => true],
            ['id' => 275, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Congreso del Estado', 'siglas' => null, 'activo' => true],
            ['id' => 276, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Estatal Electoral', 'siglas' => 'IEE', 'activo' => true],
            ['id' => 277, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Dirección de Desarrollo Humano y Educación', 'siglas' => null, 'activo' => true],
            ['id' => 278, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Instituto Municipal de las Mujeres', 'siglas' => 'IMM', 'activo' => true],
            ['id' => 279, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Instituto de Planeación Integral del Municipio de Chihuahua', 'siglas' => 'IMPLAN', 'activo' => true],
            ['id' => 280, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Tribunal Estatal de Justicia Administrativa', 'siglas' => 'TEJA', 'activo' => true],
            ['id' => 281, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Tribunal Superior de Justicia', 'siglas' => 'TSJ', 'activo' => true],
            ['id' => 282, 'nivel_gobierno_id' => 3, 'municipio_id' => 19, 'nombre' => 'Municipio de Chihuahua - Centro de Atención y Prevención Psicológicas', 'siglas' => 'CAPPSI', 'activo' => true],
            ['id' => 283, 'nivel_gobierno_id' => 2, 'municipio_id' => 21, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Delicias', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 284, 'nivel_gobierno_id' => 2, 'municipio_id' => 1, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Ahumada', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 285, 'nivel_gobierno_id' => 2, 'municipio_id' => 2, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Aldama', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 286, 'nivel_gobierno_id' => 2, 'municipio_id' => 11, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Camargo', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 287, 'nivel_gobierno_id' => 2, 'municipio_id' => 17, 'nombre' => 'Junta Municipal de Agua y Saneamiento de Alvaro Obregón', 'siglas' => 'JMAS', 'activo' => true],
            ['id' => 288, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo de Ayuda de Asistencia y Reparación a Victimas del Estado de Chihuahua', 'siglas' => null, 'activo' => true],
            ['id' => 289, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Comité de Adquisiciones de Arrendamientos y Servicios', 'siglas' => null, 'activo' => true],
            ['id' => 290, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Comité de Obras Públicas y Servicios relacionados de las mismas', 'siglas' => null, 'activo' => true],
            ['id' => 291, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Instituto de Desarrollo Económico y Agropecuario', 'siglas' => 'IDEA', 'activo' => true],
            ['id' => 292, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Desarrollo Integral de la Familia', 'siglas' => 'DIF', 'activo' => true],
            ['id' => 293, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Instituto de las Mujeres', 'siglas' => 'IMM', 'activo' => true],
            ['id' => 294, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Consejo Municipal de Estacionómetros', 'siglas' => null, 'activo' => true],
            ['id' => 295, 'nivel_gobierno_id' => 3, 'municipio_id' => 21, 'nombre' => 'Municipio de Delicias - Instituto Municipal del Deporte y la Juventud', 'siglas' => 'INMUDEJ', 'activo' => true],
            ['id' => 296, 'nivel_gobierno_id' => 3, 'municipio_id' => 62, 'nombre' => 'Municipio de Saucillo - Desarrollo Integral de la Familia', 'siglas' => 'DIF', 'activo' => true],
            ['id' => 297, 'nivel_gobierno_id' => 3, 'municipio_id' => 62, 'nombre' => 'Municipio de Saucillo - Estacionómetros', 'siglas' => null, 'activo' => true],
            ['id' => 298, 'nivel_gobierno_id' => 3, 'municipio_id' => 62, 'nombre' => 'Municipio de Saucillo - Instituto Municipal del Deporte', 'siglas' => null, 'activo' => true],
            ['id' => 299, 'nivel_gobierno_id' => 3, 'municipio_id' => 49, 'nombre' => 'Municipio de Nonoava - Dirección de Obras Públicas', 'siglas' => null, 'activo' => true],
            ['id' => 300, 'nivel_gobierno_id' => 3, 'municipio_id' => 37, 'nombre' => 'Municipio de Juárez - Dirección de Obras Públicas', 'siglas' => null, 'activo' => true],
            ['id' => 301, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense para la Transparencia y Acceso a la Información Pública', 'siglas' => 'ICHITAIP', 'activo' => true],
            ['id' => 302, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Tribunal Estatal Electoral', 'siglas' => 'TEE', 'activo' => true],
            ['id' => 303, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Instituto Chihuahuense de Salud Mental', 'siglas' => null, 'activo' => true],
            ['id' => 304, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fondo de Atención para Niños y Niñas Hijos de Policías Caídos en Cumplimiento del Deber', 'siglas' => null, 'activo' => true],
            ['id' => 305, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Centro de Conciliación Laboral del Estado de Chihuahua', 'siglas' => 'CCL', 'activo' => true],
            ['id' => 306, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Fideicomiso de Promoción de las Actividades Turísticas', 'siglas' => 'FIDEICOMISO TURISMO', 'activo' => true],
            ['id' => 307, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Autónoma de Chihuahua', 'siglas' => 'UACH', 'activo' => true],
            ['id' => 308, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Universidad Autónoma de Ciudad Juárez', 'siglas' => 'UACJ', 'activo' => true],
            ['id' => 309, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Comisión Estatal de Atención contra las Adicciones', 'siglas' => 'CECA', 'activo' => true],
            ['id' => 329, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Centro provicional para la actualizacion de datos reales', 'siglas' => 'XXXX', 'activo' => false],
            ['id' => 331, 'nivel_gobierno_id' => 2, 'municipio_id' => null, 'nombre' => 'Centro vacio en el Excel', 'siglas' => 'XXXX', 'activo' => true],
        ];

        DB::table('entes')->insert($entes);
    }
}