<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SedeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sedes')->insert([
            ['id' => 1, 'ente_id' => 12, 'nombre' => 'SSPE / Transporte ACTUALIZAR', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 2, 'ente_id' => 2, 'nombre' => 'Administradora de Servicios Aeroportuarios de Chihuahua S.A. de C.V', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 3, 'ente_id' => 12, 'nombre' => 'Administrativo - Dirección de Transporte Cd. Juárez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 4, 'ente_id' => 15, 'nombre' => 'Administrativo Medidas Judiciales Zona Occidente Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 5, 'ente_id' => 4, 'nombre' => 'Agencia Estatal de Desarrollo Energético', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 6, 'ente_id' => 15, 'nombre' => 'Agencia Estatal de Investigación', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 7, 'ente_id' => 15, 'nombre' => 'Agencia Estatal de Investigación en Guachochi (Policía Estatal Única)', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 8, 'ente_id' => 36, 'nombre' => 'Almacén Central del ICHISAL', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 9, 'ente_id' => 7, 'nombre' => 'Almacén de Infraestructura Secretaría de Educación y Deporte', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 10, 'ente_id' => 3, 'nombre' => 'Almacén de Valores de Recaudación de Rentas (Antes Bodega de Embargos)', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 11, 'ente_id' => 2, 'nombre' => 'Almacén General', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 12, 'ente_id' => 2, 'nombre' => 'Almacenes Distribuidora de la Frontera S. A.', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 13, 'ente_id' => 2, 'nombre' => 'Américas', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 14, 'ente_id' => 36, 'nombre' => 'Antiguo Hospital Infantil', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 15, 'ente_id' => 10, 'nombre' => 'Apoyo a Dependencias (SCOP)', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 16, 'ente_id' => 2, 'nombre' => 'Archivo General del Estado de Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 17, 'ente_id' => 2, 'nombre' => 'Archivo General Juárez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 18, 'ente_id' => 2, 'nombre' => 'Archivo Notariado - Bodega de libros', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 19, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Catedral', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 20, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Creel', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 21, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Parral', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 22, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) PRONAF', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 24, 'ente_id' => 2, 'nombre' => 'ASP de Juárez S. A. de C. V.', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 25, 'ente_id' => 2, 'nombre' => 'At&T', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 26, 'ente_id' => 110, 'nombre' => 'Atención a Víctimas Plaza Greca', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 27, 'ente_id' => 5, 'nombre' => 'Atención para las Personas Adulto Mayor y MACHI - Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 28, 'ente_id' => 2, 'nombre' => 'Bafar Santa Anita Big Game Hunting S. de R. L. de C. V.', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 29, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 30, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Bahuichivo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 31, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Basaseachi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 32, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Galeana', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 33, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Madera', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 34, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Gomez Farías', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 35, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Guerrero', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 36, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Namiquipa', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 37, 'ente_id' => 2, 'nombre' => 'Bodega', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 38, 'ente_id' => 3, 'nombre' => 'Bodega Bienes Muebles', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 39, 'ente_id' => 15, 'nombre' => 'Bodega de Archivo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 40, 'ente_id' => 15, 'nombre' => 'Bodega de Evidencias', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 41, 'ente_id' => 2, 'nombre' => 'Bogotá', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 42, 'ente_id' => 10, 'nombre' => 'Boquilla de Villa (SCOP)', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 43, 'ente_id' => 2, 'nombre' => 'Bufete Jurídico Universitario', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 44, 'ente_id' => 130, 'nombre' => 'Buró de Convenciones Buró de Convenciones A.C. - Cd. Juárez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 45, 'ente_id' => 12, 'nombre' => 'C 4 - Camargo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 46, 'ente_id' => 12, 'nombre' => 'C-4 Zona Norte.', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 47, 'ente_id' => 3, 'nombre' => 'Carreteras de Cuota - Secretaría de Hacienda', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 48, 'ente_id' => 113, 'nombre' => 'Centro de Patrimonio Cultural Casa Chihuahua', 'direccion_texto' => 'Calle Libertad 901, Col. Centro, Chihuahua, Chih.', 'conmutador' => '614 429 3300', 'sitio_web' => null, 'activo' => 1],
            ['id' => 49, 'ente_id' => 1, 'nombre' => 'Casa de Gobierno', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 50, 'ente_id' => 9, 'nombre' => 'Casa de la Cultura en Guachochi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 51, 'ente_id' => 2, 'nombre' => 'Casa Particular', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 52, 'ente_id' => 2, 'nombre' => 'Casas Grandes', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 53, 'ente_id' => 3, 'nombre' => 'Caseta de Estacionamiento Allende', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 54, 'ente_id' => 3, 'nombre' => 'Caseta de Galeana', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 55, 'ente_id' => 12, 'nombre' => 'Caseta de Inspección Ganadera El Granillo - Depto. de Ganadería', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 56, 'ente_id' => 3, 'nombre' => 'Caseta Ojo Laguna', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 57, 'ente_id' => 3, 'nombre' => 'Caseta San Jerónimo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 58, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Jiménez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 59, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Parral Jiménez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 60, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 61, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Chihuahua Ojinaga', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 62, 'ente_id' => 3, 'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Cuota de Conchos Camargo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 63, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Sacramento', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 64, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Savalza', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 65, 'ente_id' => 3, 'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Villa Ahumada', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 66, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo Ingresos de Carreteras de Cuota de Saucillo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 67, 'ente_id' => 38, 'nombre' => 'CAVIM - ICHIMU - Guachochi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 68, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 02 La Junta', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 69, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 03 Valle de Allende', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 70, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 04 Guadalupe y Calvo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 71, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 05 San Juanito', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 72, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 06 Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 73, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 07 San Isidro', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 74, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 08 Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 75, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 09 Lomas de Poleo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 76, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 10 Gómez Farías', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 77, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 11 Ciudad del Conocimiento', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 78, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 12 Flores Magón', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 79, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 13 San Guillermo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 80, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 14 Villa Esperanza', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 81, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 15 Ascención', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 82, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 16 Le Barón', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 83, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 17 Baborigame', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 84, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 18 Villa Aldama', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 85, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 19 Industrias', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 86, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 20 Oriente', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 87, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 21 Riberas Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 88, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 22 Ayuntamiento', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 89, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 23 Riberas Juárez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 90, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 24 Toribio Ortega', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 91, 'ente_id' => 29, 'nombre' => 'CECYTECH Dirección General', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 92, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 01 Turuachi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 93, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 02 El Vergel', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 94, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 03 Rocheachi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 95, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 04 Carichí', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 96, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 05 Tomochi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 97, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 06 Benito Juárez', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 98, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 09 Atascaderos', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 99, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 10 Samachique', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 100, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 11 Bahuichivo', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 101, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 12 Satevó', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 102, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 13 Naica', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 103, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 15 Mesa de San Rafael', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 104, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 17 Morelos', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 105, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 18 Valle del Rosario', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 106, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 19 Moris', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 107, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 20 Santa Isabel', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 108, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 22 Nonoava', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 109, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 23 San Francisco de Borja', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 110, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 24 Urique', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 111, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 25 Congregación Ortíz', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 112, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 26 Bachíniva', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 113, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 28 Ignacio Zaragoza', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 114, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 29 Ojo de Agua', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 115, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 30 Riva Palacio', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 116, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 31 Témoris', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 117, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 32 Janos', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 118, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 33 Matachí', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 119, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 34 San Rafael', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 120, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 35 Uruachi', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 121, 'ente_id' => 12, 'nombre' => 'CEDEFAM', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 122, 'ente_id' => 7, 'nombre' => 'CEDEX e Inspección de Zona 58', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 123, 'ente_id' => 3, 'nombre' => 'Centro Comercial Galerías Tec - Recaudación de Rentas', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 124, 'ente_id' => 9, 'nombre' => 'Centro Cultural Palacio de Alvarado', 'direccion_texto' => 'Calle Riva Palacio 2, Col. Centro, Hidalgo del Parral, Chih.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 125, 'ente_id' => 9, 'nombre' => 'Centro Cultural Paso del Norte - Secretaría de Cultura Cd. Juárez', 'direccion_texto' => 'Anillo Envolvente del Pronaf s/n, Col. Progresista, Ciudad Juárez, Chih.', 'conmutador' => '656 617 6603', 'sitio_web' => null, 'activo' => 1],
            ['id' => 126, 'ente_id' => 9, 'nombre' => 'Centro Cultural Quinta Carolina', 'direccion_texto' => 'Calle Monte Everest esq. Av. Fedor Dostoyevsky, Col. Quintas Carolinas, Chihuahua, Chih.', 'conmutador' => '614 499 3442', 'sitio_web' => null, 'activo' => 1],
            ['id' => 127, 'ente_id' => 7, 'nombre' => 'Centro de Actualización del Magisterio', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 128, 'ente_id' => 3, 'nombre' => 'Centro de Capacitación y Desarrollo CECADE (SH)', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 129, 'ente_id' => 15, 'nombre' => 'Centro de Capacitación, Profesionalización y Certificación de la FGE', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 130, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Cuauhtémoc', 'direccion_texto' => 'Av. Tecnológico 349, Local C, Cuauhtémoc, Chih.', 'conmutador' => '625 688 2946', 'sitio_web' => null, 'activo' => 1],
            ['id' => 131, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Delicias', 'direccion_texto' => 'Calle Primera Oriente 103, Sector Oriente 1, Delicias, Chih.', 'conmutador' => '639 688 1923', 'sitio_web' => null, 'activo' => 1],
            ['id' => 132, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Nuevo Casas Grandes', 'direccion_texto' => 'Av. Constitución 903, Local 6, Col. Centro, Nuevo Casas Grandes, Chih.', 'conmutador' => '636 692 7674', 'sitio_web' => null, 'activo' => 1],
            ['id' => 133, 'ente_id' => 32, 'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Chihuahua', 'direccion_texto' => 'Av. Central 8901, Parque Industrial Chihuahua Sur, Chihuahua, Chih.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 134, 'ente_id' => 32, 'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 135, 'ente_id' => 134, 'nombre' => 'Presidencia Municipal de Ahumada', 'direccion_texto' => 'Avenida Hidalgo 100, Zona Centro, C.P. 32800', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 136, 'ente_id' => 136, 'nombre' => 'Presidencia Municipal de Allende', 'direccion_texto' => 'La Antena, 33920 Valle de Ignacio Allende, Chih.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 137, 'ente_id' => 135, 'nombre' => 'Presidencia Municipal de Aldama', 'direccion_texto' => 'Calle Segunda #2, Colonia Centro, C.P. 32900, Aldama, Chihuahua', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 138, 'ente_id' => 137, 'nombre' => 'Presidencia Municipal de Aquiles Serdán', 'direccion_texto' => 'Calle Juárez s/n, Colonia Centro, en la cabecera municipal de Santa Eulalia, C.P. 31650', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 139, 'ente_id' => 138, 'nombre' => 'Presidencia Municipal de Ascensión', 'direccion_texto' => 'Avenida México #115, Colonia Centro, C.P. 31820, en Ascensión, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 140, 'ente_id' => 139, 'nombre' => 'Presidencia Municipal de Bachiniva', 'direccion_texto' => 'Calle Zaragoza s/n, Zona Centro, C.P. 31660, Bachíniva, Chihuahua', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 141, 'ente_id' => 140, 'nombre' => 'Presidencia Municipal de Balleza', 'direccion_texto' => 'Calle Independencia No. 1, Colonia Centro, C.P. 33560, Balleza, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 142, 'ente_id' => 141, 'nombre' => 'Presidencia Municipal de Batopilas', 'direccion_texto' => 'Calle Juárez No. 18, Colonia Centro, C.P. 33400, en Batopilas, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 143, 'ente_id' => 142, 'nombre' => 'Presidencia Municipal de Bocoyna', 'direccion_texto' => 'Conocido S/N, Colonia Centro, C.P. 33204, en la localidad de Bocoyna, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 144, 'ente_id' => 143, 'nombre' => 'Presidencia Municipal de Buenaventura', 'direccion_texto' => 'calle Anáhuac y avenida Juárez S/N, colonia Centro, C.P. 31890, en San Buenaventura, Chihuahua', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 145, 'ente_id' => 144, 'nombre' => 'Presidencia Municipal de Camargo', 'direccion_texto' => 'calle Allende No. 1, Colonia Centro, C.P. 33700, Ciudad Camargo, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 146, 'ente_id' => 145, 'nombre' => 'Presidencia Municipal de Carichí', 'direccion_texto' => 'Calle Constitución y Segunda, en la zona centro, C.P. 33280, Carichí, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 147, 'ente_id' => 146, 'nombre' => 'Presidencia Municipal de Casas Grandes', 'direccion_texto' => 'Av. Constitución #100, Col. Centro, C.P. 31850, en Casas Grandes, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 148, 'ente_id' => 152, 'nombre' => 'Presidencia Municipal de Chihuahua', 'direccion_texto' => 'Avenida Independencia número 209, Colonia Centro, C.P. 31000, Chihuahua, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 149, 'ente_id' => 252, 'nombre' => 'Presidencia Municipal de Chínipas', 'direccion_texto' => 'Calle Ayuntamiento número 5, en la localidad de Chínipas de Almada, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 150, 'ente_id' => 147, 'nombre' => 'Presidencia Municipal de Coronado', 'direccion_texto' => 'Calle Coronado #18, esquina con Avenida Zaragoza y Centenario, en Villa Coronado, C.P. 33990, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 151, 'ente_id' => 148, 'nombre' => 'Presidencia Municipal de Coyame del Sotol', 'direccion_texto' => 'Calle Miguel Hidalgo S/N, Colonia Centro, C.P. 32850, Santiago de Coyame, Coyame del Sotol, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 152, 'ente_id' => 150, 'nombre' => 'Presidencia Municipal de Cuauhtémoc', 'direccion_texto' => 'Avenida Allende y Agustín Melgar número 15, en la Zona Centro, Cuauhtémoc, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 153, 'ente_id' => 151, 'nombre' => 'Presidencia Municipal de Cusihuiriachi', 'direccion_texto' => 'Calle Hidalgo y Cuarta s/n Zona Centro, C.P. 33240, Cusihuiriachi, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 154, 'ente_id' => 154, 'nombre' => 'Presidencia Municipal de Delicias', 'direccion_texto' => 'Círculo del Reloj Público Oriente #1, Colonia Centro, C.P. 33000, en Delicias, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 155, 'ente_id' => 155, 'nombre' => 'Presidencia Municipal de Dr. Belisario Domínguez', 'direccion_texto' => 'Calle Sin Nombre S/N, Colonia Centro, Cabecera municipal San Lorenzo, Dr. Belisario Domínguez, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 156, 'ente_id' => 197, 'nombre' => 'Presidencia Municipal de El Tule', 'direccion_texto' => 'Palacio Municipal S/N, Col. Centro, C.P. 33550, El Tule, Chihuahua,', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 157, 'ente_id' => 156, 'nombre' => 'Presidencia Municipal de Galeana', 'direccion_texto' => 'Avenida Progreso 301, C.P. 31879 Hermenegildo Galeana, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 158, 'ente_id' => 159, 'nombre' => 'Presidencia Municipal de Gran Morelos', 'direccion_texto' => 'San Nicolás de Carretas, C.P. 33260, Gran Morelos, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 159, 'ente_id' => 158, 'nombre' => 'Presidencia Municipal de Gómez Farías', 'direccion_texto' => 'Ave. Libertad y constitución #302 Col. centro Gómez Farías, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 160, 'ente_id' => 160, 'nombre' => 'Presidencia Municipal de Guachochi', 'direccion_texto' => 'Calle Abraham González número 5, colonia Centro, C.P. 33180, en Guachochi, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 161, 'ente_id' => 161, 'nombre' => 'Presidencia Municipal de Guadalupe', 'direccion_texto' => 'Avenida Hidalgo s/n, Colonia Centro, C.P. 32880, Guadalupe, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 162, 'ente_id' => 162, 'nombre' => 'Presidencia Municipal de Guadalupe y Calvo', 'direccion_texto' => 'Plaza Donato Guerra s/n Guadalupe y Calvo, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 163, 'ente_id' => 163, 'nombre' => 'Presidencia Municipal de Guazapares', 'direccion_texto' => 'Calle Franco Urías s/n, Colonia Centro, C.P. 33380, en Témoris, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 164, 'ente_id' => 164, 'nombre' => 'Presidencia Municipal de Guerrero', 'direccion_texto' => 'Calle Allende y doctor Brondo sin número, C.P. 31680, en Ciudad Guerrero, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 165, 'ente_id' => 165, 'nombre' => 'Presidencia Municipal de Hidalgo del Parral', 'direccion_texto' => 'Calles Francisco Sarabia y República de Cuba, en la colonia Américas, C.P. 33880, en Parral, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 166, 'ente_id' => 166, 'nombre' => 'Presidencia Municipal de Huejotitán', 'direccion_texto' => 'Calle Independencia s/n, zona centro, C.P. 33540, Huejotitán, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 167, 'ente_id' => 167, 'nombre' => 'Presidencia Municipal de Ignacio Zaragoza', 'direccion_texto' => 'Calle 24 de Febrero 351, 31920 Ignacio Zaragoza, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 168, 'ente_id' => 168, 'nombre' => 'Presidencia Municipal de Janos', 'direccion_texto' => 'Avenida Ojinaga S/N, Zona Centro, C.P. 31840, en Janos, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 169, 'ente_id' => 169, 'nombre' => 'Presidencia Municipal de Jiménez', 'direccion_texto' => 'Calle Independencia S/N ; Colonia Centro, C.P. 33980, Jiménez, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 170, 'ente_id' => 171, 'nombre' => 'Presidencia Municipal de Julimes', 'direccion_texto' => 'Calle Hidalgo y Ocampo No. 1, Colonia Centro, C.P. 32950, Julimes, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 171, 'ente_id' => 170, 'nombre' => 'Presidencia Municipal de Juárez', 'direccion_texto' => 'Avenida Francisco Villa número 950 Norte, colonia Centro, C.P. 32000, Juárez, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 172, 'ente_id' => 149, 'nombre' => 'Presidencia Municipal de La Cruz', 'direccion_texto' => 'Calles Zaragoza y Nigromante, Zona Centro, C.P. 33670, La Cruz, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 173, 'ente_id' => 172, 'nombre' => 'Presidencia Municipal de López', 'direccion_texto' => 'Calles Hidalgo y Victoria S/N, Zona Centro, C.P. 33940, Villa López, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 174, 'ente_id' => 173, 'nombre' => 'Presidencia Municipal de Madera', 'direccion_texto' => 'Calle Aldama #100, Colonia Centro, C.P. 31940, Madera, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 175, 'ente_id' => 174, 'nombre' => 'Presidencia Municipal de Maguarichi', 'direccion_texto' => 'Domicilio conocido S/N, Col. Centro, C.P. 33370, Maguarichi, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 176, 'ente_id' => 175, 'nombre' => 'Presidencia Municipal de Manuel Benavides', 'direccion_texto' => 'Calle Porvenir y Progreso S/N, Colonia Centro, C.P. 32980, Manuel Benavides, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 177, 'ente_id' => 176, 'nombre' => 'Presidencia Municipal de Matachí', 'direccion_texto' => 'Calles Hidalgo y 2a S/N, Zona Centro, Matachí, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 178, 'ente_id' => 177, 'nombre' => 'Presidencia Municipal de Matamoros', 'direccion_texto' => 'Calle Duraznos 1, C.P. 33960, Centro, Matamoros, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 179, 'ente_id' => 178, 'nombre' => 'Presidencia Municipal de Meoqui', 'direccion_texto' => 'Calle Hidalgo S/N, Colonia Centro, C.P. 33130, Meoqui, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 180, 'ente_id' => 179, 'nombre' => 'Presidencia Municipal de Morelos', 'direccion_texto' => 'Calle Principal S/N, C.P. 33450, Morelos, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 181, 'ente_id' => 180, 'nombre' => 'Presidencia Municipal de Moris', 'direccion_texto' => 'Domicilio Conocido S/N, C.P. 33340, Moris, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 182, 'ente_id' => 181, 'nombre' => 'Presidencia Municipal de Namiquipa', 'direccion_texto' => 'Calle Abasolo número 2, Colonia Centro, C.P. 31975, Namiquipa, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 183, 'ente_id' => 182, 'nombre' => 'Presidencia Municipal de Nonoava', 'direccion_texto' => 'Calle Tercera S/N, Zona Centro, C.P. 33170, Nonoava, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 184, 'ente_id' => 183, 'nombre' => 'Presidencia Municipal de Nuevo Casas Grandes', 'direccion_texto' => 'Av. Constitución #304, Col. Centro, C.P. 31700, Nuevo Casas Grandes, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 185, 'ente_id' => 184, 'nombre' => 'Presidencia Municipal de Ocampo', 'direccion_texto' => 'Domicilio conocido en la cabecera municipal Ocampo, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 186, 'ente_id' => 185, 'nombre' => 'Presidencia Municipal de Ojinaga', 'direccion_texto' => 'Calle Trasviña y Retes y Zaragoza S/N, Colonia Centro, C.P. 32800, Ojinaga, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 187, 'ente_id' => 186, 'nombre' => 'Presidencia Municipal de Praxedis G. Guerrero', 'direccion_texto' => 'Calle Hidalgo No. 42, Colonia Centro, C.P. 32780, en Praxedis G. Guerrero, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 188, 'ente_id' => 187, 'nombre' => 'Presidencia Municipal de Riva Palacio', 'direccion_texto' => 'Calle Hermanos Calderón #49, Colonia Centro, C.P. 31640, Riva Palacio, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 189, 'ente_id' => 188, 'nombre' => 'Presidencia Municipal de Rosales', 'direccion_texto' => 'Calle México y la calle Benito Juárez S/N, C.P. 33120, Rosales, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 190, 'ente_id' => 189, 'nombre' => 'Presidencia Municipal de Rosario', 'direccion_texto' => 'Domicilio Conocido S/N, Zona Centro, C.P. 33530, Rosario, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 191, 'ente_id' => 190, 'nombre' => 'Presidencia Municipal de San Francisco de Borja', 'direccion_texto' => 'Calle Segunda No. 27, Sector 1, C.P. 33160, San Francisco de Borja, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 192, 'ente_id' => 191, 'nombre' => 'Presidencia Municipal de San Francisco de Conchos', 'direccion_texto' => 'Calle Hidalgo S/N, Colonia Centro, C.P. 33680, en San Francisco de Conchos, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 193, 'ente_id' => 192, 'nombre' => 'Presidencia Municipal de San Francisco del Oro', 'direccion_texto' => 'Calle Vicente Guerrero S/N, Zona Centro, C.P. 33500, en San Francisco del Oro, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 194, 'ente_id' => 193, 'nombre' => 'Presidencia Municipal de Santa Bárbara', 'direccion_texto' => 'Calle Maclovio Herrera y Allende S/N, Colonia Centro, C.P. 33580, Santa Bárbara, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 195, 'ente_id' => 157, 'nombre' => 'Presidencia Municipal de Santa Isabel', 'direccion_texto' => 'Calle Independencia y Libertad S/N, Colonia Centro, C.P. 33270, Santa Isabel, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 196, 'ente_id' => 194, 'nombre' => 'Presidencia Municipal de Satevó', 'direccion_texto' => 'Calle Victoria S/N, Colonia Centro, C.P. 33150, Satevó, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 197, 'ente_id' => 195, 'nombre' => 'Presidencia Municipal de Saucillo', 'direccion_texto' => 'Avenida Séptima #100, Colonia Centro, C.P. 33620, Saucillo, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 198, 'ente_id' => 196, 'nombre' => 'Presidencia Municipal de Temósachic', 'direccion_texto' => 'Ave. Juárez #101, C.P. 31980, Zona Centro, Temósachic, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 199, 'ente_id' => 198, 'nombre' => 'Presidencia Municipal de Urique', 'direccion_texto' => 'Domicilio Conocido C.P. 33420, Urique, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 200, 'ente_id' => 199, 'nombre' => 'Presidencia Municipal de Uruachi', 'direccion_texto' => 'Domicilio Conocido S/N, Colonia Centro, C.P. 33300, Uruachi, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
            ['id' => 201, 'ente_id' => 200, 'nombre' => 'Presidencia Municipal de Valle de Zaragoza', 'direccion_texto' => 'Calle Vicente Guerrero #12, esquina con calle Juárez, Colonia Centro, C.P. 33940, Valle de Zaragoza, Chihuahua.', 'conmutador' => null, 'sitio_web' => null, 'activo' => 1],
        ]);
    }
}
