<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SedeSeeder extends Seeder
{
    public function run(): void
    {
        $sedes = [
            [
                'id' => 1,
                'ente_id' => 329,
                'nombre' => 'ACTUALIZAR',
                'direccion_texto' => 'Horario: N/A | Colonia ID: 73144',
                'activo' => false,
            ],
            [
                'id' => 2,
                'ente_id' => 132,
                'nombre' => 'Administradora de Servicios Aeroportuarios de Chihuahua S.A. de C.V',
                'direccion_texto' => 'Calle Allende #703. Horario: 9:00 - 15:00 | Colonia ID: 1928',
                'activo' => false,
            ],
            [
                'id' => 3,
                'ente_id' => 329,
                'nombre' => 'Administrativo - Dirección de Transporte Cd. Juárez',
                'direccion_texto' => 'Eje Vial Juan Gabriel y Aserraderos. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 4,
                'ente_id' => 329,
                'nombre' => 'Administrativo Medidas Judiciales Zona Occidente Cuauhtémoc',
                'direccion_texto' => 'Calle Morelos y 23 #2105. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 5,
                'ente_id' => 329,
                'nombre' => 'Agencia Estatal de Desarrollo Energético',
                'direccion_texto' => 'Avenida Melchor Ocampo #2004. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 6,
                'ente_id' => 329,
                'nombre' => 'Agencia Estatal de Investigación',
                'direccion_texto' => 'Carretera Km 3.5 Carretera Aldama. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 7,
                'ente_id' => 329,
                'nombre' => 'Agencia Estatal de Investigación en Guachochi (Policía Estatal Única)',
                'direccion_texto' => 'Avenida 20 de Noviembre y 1° de Mayo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 8,
                'ente_id' => 329,
                'nombre' => 'Almacén Central del ICHISAL',
                'direccion_texto' => 'Calle Torosaurio Perif. Francisco R. Almada #13200. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 9,
                'ente_id' => 329,
                'nombre' => 'Almacén de Infraestructura Secretaría de Educación y Deporte',
                'direccion_texto' => 'Avenida 20 de noviembre y 32 #3200. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 10,
                'ente_id' => 329,
                'nombre' => 'Almacén de Valores de Recaudación de Rentas (Antes Bodega de Embargos)',
                'direccion_texto' => 'Avenida Independencia #5605. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 11,
                'ente_id' => 329,
                'nombre' => 'Almacén General',
                'direccion_texto' => 'Avenida De las Industrias #4701. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 12,
                'ente_id' => 329,
                'nombre' => 'Almacenes Distribuidora de la Frontera S. A.',
                'direccion_texto' => 'Avenida Plutarco Elías Calles, Col. Progresista #744. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 13,
                'ente_id' => 329,
                'nombre' => 'Américas',
                'direccion_texto' => 'Avenida Niños Héroes #1103 Piso 2. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 14,
                'ente_id' => 329,
                'nombre' => 'Antiguo Hospital Infantil',
                'direccion_texto' => 'Avenida Matamoros #2239. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 15,
                'ente_id' => 329,
                'nombre' => 'Apoyo a Dependencias (SCOP)',
                'direccion_texto' => 'Calle Rosales y 53 #5108. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 16,
                'ente_id' => 329,
                'nombre' => 'Archivo General del Estado de Chihuahua',
                'direccion_texto' => 'Calle 21 #2501. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 17,
                'ente_id' => 329,
                'nombre' => 'Archivo General Juárez',
                'direccion_texto' => 'Calle Camino Viejo a San Lorenzo #6545. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 18,
                'ente_id' => 329,
                'nombre' => 'Archivo Notariado - Bodega de libros',
                'direccion_texto' => 'Avenida Tecnológico #1904. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 19,
                'ente_id' => 329,
                'nombre' => 'Arte Popular Chihuahua (FODARCH) Catedral',
                'direccion_texto' => 'Calle Victoria #14. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 20,
                'ente_id' => 329,
                'nombre' => 'Arte Popular Chihuahua (FODARCH) Creel',
                'direccion_texto' => 'Calle Ferrocarril #198. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 21,
                'ente_id' => 329,
                'nombre' => 'Arte Popular Chihuahua (FODARCH) Parral',
                'direccion_texto' => 'Calle Pedro T. Gómez y Mercaderes. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 22,
                'ente_id' => 329,
                'nombre' => 'Arte Popular Chihuahua (FODARCH) PRONAF',
                'direccion_texto' => 'Circuito José Reyes Estrada #445. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 24,
                'ente_id' => 329,
                'nombre' => 'ASP de Juárez S. A. de C. V.',
                'direccion_texto' => 'Avenida De los Insurgentes #1922. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 25,
                'ente_id' => 329,
                'nombre' => 'At&T',
                'direccion_texto' => 'Boulevard Manuel Gómez Morín #7045. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 26,
                'ente_id' => 329,
                'nombre' => 'Atención a Víctimas Plaza Greca',
                'direccion_texto' => 'Avenida Benito Juárez #1006. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 27,
                'ente_id' => 329,
                'nombre' => 'Atención para las Personas Adulto Mayor y MACHI - Cuauhtémoc',
                'direccion_texto' => 'Calle 62 y Tenochtitlan. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 28,
                'ente_id' => 329,
                'nombre' => 'Bafar Santa Anita Big Game Hunting S. de R. L. de C. V.',
                'direccion_texto' => 'Carretera Km. 7.5 Carretera a Cuauhtémoc. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 29,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones Cuauhtémoc',
                'direccion_texto' => 'Avenida Domicilio conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 30,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones en Bahuichivo',
                'direccion_texto' => 'Avenida Domicilio conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 31,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones en Basaseachi',
                'direccion_texto' => 'Avenida Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 32,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones en Galeana',
                'direccion_texto' => 'Avenida Progreso #308. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 33,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones en Madera',
                'direccion_texto' => 'Avenida Internacional y Calle 27a.. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 34,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones Gomez Farías',
                'direccion_texto' => 'Avenida Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 35,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones Guerrero',
                'direccion_texto' => 'Avenida Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 36,
                'ente_id' => 329,
                'nombre' => 'Base de Operaciones Namiquipa',
                'direccion_texto' => 'Avenida Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 37,
                'ente_id' => 329,
                'nombre' => 'Bodega',
                'direccion_texto' => 'Avenida Niños Héroes #706. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 38,
                'ente_id' => 329,
                'nombre' => 'Bodega Bienes Muebles',
                'direccion_texto' => 'Calle 3a y 73. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 39,
                'ente_id' => 329,
                'nombre' => 'Bodega de Archivo',
                'direccion_texto' => 'Carretera Km 3.5 Carretera Aldama. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 40,
                'ente_id' => 329,
                'nombre' => 'Bodega de Evidencias',
                'direccion_texto' => 'Carretera Km 3.5 Carretera Aldama. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 41,
                'ente_id' => 329,
                'nombre' => 'Bogotá',
                'direccion_texto' => 'Calle Bogotá #1905. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 42,
                'ente_id' => 329,
                'nombre' => 'Boquilla de Villa (SCOP)',
                'direccion_texto' => 'Prolongacion Zootecnia Km 1.5. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 43,
                'ente_id' => 329,
                'nombre' => 'Bufete Jurídico Universitario',
                'direccion_texto' => 'Avenida Henry Dunant casi esquina con López mateos #4016. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 44,
                'ente_id' => 329,
                'nombre' => 'Buró de Convenciones A.C. - Cd. Juárez',
                'direccion_texto' => 'Avenida De las Américas #2551. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 45,
                'ente_id' => 329,
                'nombre' => 'C 4 - Camargo',
                'direccion_texto' => 'Calle Juan H Álvarez y Juan de Dios Peza. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 46,
                'ente_id' => 329,
                'nombre' => 'C-4 Zona Norte.',
                'direccion_texto' => 'Calle Fortín de la Soledad y Valle de Cedro #1437. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 47,
                'ente_id' => 329,
                'nombre' => 'Carreteras de Cuota - Secretaría de Hacienda',
                'direccion_texto' => 'Calle William Shakespeare #153. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 48,
                'ente_id' => 329,
                'nombre' => 'Casa Chihuahua',
                'direccion_texto' => 'Calle Libertad #901. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 49,
                'ente_id' => 329,
                'nombre' => 'Casa de Gobierno',
                'direccion_texto' => 'Calle 26 y Zarco #2601. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 50,
                'ente_id' => 329,
                'nombre' => 'Casa de la Cultura en Guachochi',
                'direccion_texto' => 'Calle Francisco Sarabia. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 51,
                'ente_id' => 329,
                'nombre' => 'Casa Particular',
                'direccion_texto' => 'Avenida Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 52,
                'ente_id' => 329,
                'nombre' => 'Casas Grandes',
                'direccion_texto' => 'Calle Naciones Unidas y Minerva. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 53,
                'ente_id' => 329,
                'nombre' => 'Caseta de Estacionamiento Allende',
                'direccion_texto' => 'Calle Allende y 13. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 54,
                'ente_id' => 329,
                'nombre' => 'Caseta de Galeana',
                'direccion_texto' => 'Carretera Km. 38 Carretera Flores Magón - Galeana. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 55,
                'ente_id' => 329,
                'nombre' => 'Caseta de Inspección Ganadera El Granillo - Depto. de Ganadería',
                'direccion_texto' => 'Carretera Santa Bárbara Km. 7.5. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 56,
                'ente_id' => 329,
                'nombre' => 'Caseta Ojo Laguna',
                'direccion_texto' => 'Carretera Km. 103 Carretera Chihuahua - Juárez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 57,
                'ente_id' => 329,
                'nombre' => 'Caseta San Jerónimo',
                'direccion_texto' => 'Carretera Km. 24 Libramiento a Santa Teresa. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 58,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Jiménez',
                'direccion_texto' => 'Carretera K.m. 11, Camargo-Jiménez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 59,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Parral Jiménez',
                'direccion_texto' => 'Carretera Km. 56.3, Carretera Parral Jiménez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 60,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Cuauhtémoc',
                'direccion_texto' => 'Carretera Km 68 Santa Isabel-Cuauhtémoc. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 61,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Chihuahua Ojinaga',
                'direccion_texto' => 'Carretera Km 44 Chihuahua-Ojinaga. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 62,
                'ente_id' => 329,
                'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Cuota de Conchos Camargo',
                'direccion_texto' => 'Carretera Km 73 Conchos Camargo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 63,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Sacramento',
                'direccion_texto' => 'Carretera K.m. 31, Chihuahua-Juárez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 64,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Savalza',
                'direccion_texto' => 'Carretera K.m. 222, Carretera Jiménez Gómez Palacios. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 65,
                'ente_id' => 329,
                'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Villa Ahumada',
                'direccion_texto' => 'Carretera Km. 219, Villa Ahumada. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 66,
                'ente_id' => 329,
                'nombre' => 'Caseta y Módulo Ingresos de Carreteras de Cuota de Saucillo',
                'direccion_texto' => 'Carretera K.m. 114 Delicias-Conchos. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 67,
                'ente_id' => 329,
                'nombre' => 'CAVIM - ICHIMU - Guachochi',
                'direccion_texto' => 'Avenida Jose Ma. Morelos #5. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 68,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 02 La Junta',
                'direccion_texto' => 'Carretera Estación Adolfo López Mateos Km 3.5 Carretera La Junta-Guerrero. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 69,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 03 Valle de Allende',
                'direccion_texto' => 'Calle Felipe Ángeles #28. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 70,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 04 Guadalupe y Calvo',
                'direccion_texto' => 'Avenida Presa Las Vírgenes #528. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 71,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 05 San Juanito',
                'direccion_texto' => 'Calle Felipe Ángeles. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 72,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 06 Chihuahua',
                'direccion_texto' => 'Calle Joaquín Pedrero y Avenida de las Industrias #3300. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 73,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 07 San Isidro',
                'direccion_texto' => 'Calle José Ma. Morelos #338. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 74,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 08 Cuauhtémoc',
                'direccion_texto' => 'Calle Gómez Morín. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 75,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 09 Lomas de Poleo',
                'direccion_texto' => 'Calle De la Manzana. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 76,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 10 Gómez Farías',
                'direccion_texto' => 'Calle 3a y Hospital. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 77,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 11 Ciudad del Conocimiento',
                'direccion_texto' => 'Avenida De las Ciencias. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 78,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 12 Flores Magón',
                'direccion_texto' => 'Calle Perú y Zaragoza. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 79,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 13 San Guillermo',
                'direccion_texto' => 'Calle Mina Almanceña. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 80,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 14 Villa Esperanza',
                'direccion_texto' => 'Calle Del Aire. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 81,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 15 Ascención',
                'direccion_texto' => 'Calle Tecnológico #2832. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 82,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 16 Le Barón',
                'direccion_texto' => 'Calle Miguel HIdalgo Oriente #114. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 83,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 17 Baborigame',
                'direccion_texto' => 'Calle Domicilio Conocido. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 84,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 18 Villa Aldama',
                'direccion_texto' => 'Calle Jesús Acosta #3707. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 85,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 19 Industrias',
                'direccion_texto' => 'Ampliacion Esther Ruiz de la Peña. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 86,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 20 Oriente',
                'direccion_texto' => 'Avenida Central esquina con Tabalaopa. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 87,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 21 Riberas Chihuahua',
                'direccion_texto' => 'Calle Eugenio Prado Proaño y Río Nilo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 88,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 22 Ayuntamiento',
                'direccion_texto' => 'Calle Tacuba #921. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 89,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 23 Riberas Juárez',
                'direccion_texto' => 'Calle Margarita Flores y Arturo Álvarez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 90,
                'ente_id' => 329,
                'nombre' => 'CECYT Plantel 24 Toribio Ortega',
                'direccion_texto' => 'Calle Álvaro Ríos Ramírez (Calle 52) #12405. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 91,
                'ente_id' => 329,
                'nombre' => 'CECYTECH Dirección General',
                'direccion_texto' => 'Calle República de Bolivia #213. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 92,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 01 Turuachi',
                'direccion_texto' => 'Calle Domicilio Conocido Carretera a Parral-Guadalupe y Calvo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 93,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 02 El Vergel',
                'direccion_texto' => 'Calle Independencia de México #4. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 94,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 03 Rocheachi',
                'direccion_texto' => 'Calle Domicilio Conocido Carretera Gran Visión Km 216 Creel-Guachochi. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 95,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 04 Carichí',
                'direccion_texto' => 'Calle Privada de Ochoa y Arroyo del Pueblo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 96,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 05 Tomochi',
                'direccion_texto' => 'Calle Progreso #32. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 97,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 06 Benito Juárez',
                'direccion_texto' => 'Calle Domicilio Conocido, Ejido Benito Juárez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 98,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 09 Atascaderos',
                'direccion_texto' => 'Calle Domicilio Conocido, Atascaderos. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 99,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 10 Samachique',
                'direccion_texto' => 'Calle Domicilio Conocido, Samachique. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 100,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 11 Bahuichivo',
                'direccion_texto' => 'Calle Domicilio Conocido, Bahuichivo. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 101,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 12 Satevó',
                'direccion_texto' => 'Calle Ojinaga. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 102,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 13 Naica',
                'direccion_texto' => 'Calle Morelos y Constitución #201. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 103,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 15 Mesa de San Rafael',
                'direccion_texto' => 'Calle Francisco Villa. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 104,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 17 Morelos',
                'direccion_texto' => 'Calle José Ma. Morelos y Aquiles Serdán. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 105,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 18 Valle del Rosario',
                'direccion_texto' => 'Calle Domicilio Conocido, Valle del Rosario. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 106,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 19 Moris',
                'direccion_texto' => 'Calle Domicilio Conocido, Moris. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 107,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 20 Santa Isabel',
                'direccion_texto' => 'Calle Centenario #53. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 108,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 22 Nonoava',
                'direccion_texto' => 'Calle independencia. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 109,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 23 San Francisco de Borja',
                'direccion_texto' => 'Calle Los Frailes. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 110,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 24 Urique',
                'direccion_texto' => 'Calle Domicilio Conocido, Urique. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 111,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 25 Congregación Ortíz',
                'direccion_texto' => 'Calle Emiliano Zapata y 11 de Septiembre #3905. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 112,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 26 Bachíniva',
                'direccion_texto' => 'Calle Domicilio Conocido, Bachíniva. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 113,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 28 Ignacio Zaragoza',
                'direccion_texto' => 'Calle Josefa Ortíz de Domínguez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 114,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 29 Ojo de Agua',
                'direccion_texto' => 'Calle Domicilio Conocido, Ojo de Agua. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 115,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 30 Riva Palacio',
                'direccion_texto' => 'Calle Benito Juárez. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 116,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 31 Témoris',
                'direccion_texto' => 'Calle Adolfo Lóptez Mateos y John F. Kennedy #172. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 117,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 32 Janos',
                'direccion_texto' => 'Calle Joaquín Capilla y Miguel Mejía Barón (a un costado de Carretera Federal 2). Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 118,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 33 Matachí',
                'direccion_texto' => 'Carretera Chihuahua-Madera KM 63.8. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 119,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 34 San Rafael',
                'direccion_texto' => 'Calle Domicilio Conocido, San Rafael. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 120,
                'ente_id' => 329,
                'nombre' => 'CECYTECH EMSAD 35 Uruachi',
                'direccion_texto' => 'Calle Domicilio Conocido, Uruachi. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 121,
                'ente_id' => 329,
                'nombre' => 'CEDEFAM',
                'direccion_texto' => 'Periferico Lombardo Toledano S/N #4802. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 122,
                'ente_id' => 329,
                'nombre' => 'CEDEX e Inspección de Zona 58',
                'direccion_texto' => 'Calle 12 y 20 de Noviembre #2800. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 123,
                'ente_id' => 329,
                'nombre' => 'Centro Comercial Galerías Tec - Recaudación de Rentas',
                'direccion_texto' => 'Calle Tecnológico, Frac. las Fuentes #1770. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 124,
                'ente_id' => 329,
                'nombre' => 'Centro Cultural Palacio de Alvarado',
                'direccion_texto' => 'Calle Riva Palacio y Licenciado Verdad #2. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 125,
                'ente_id' => 329,
                'nombre' => 'Centro Cultural Paso del Norte - Secretaría de Cultura Cd. Juárez',
                'direccion_texto' => 'Circuito Anillo Envolvente del PRONAF entre calles Estocolmo y Benjamín Franklin. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 126,
                'ente_id' => 329,
                'nombre' => 'Centro Cultural Quinta Carolina',
                'direccion_texto' => 'Calle Fedor Dostoyevski y Monte Everest. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 127,
                'ente_id' => 329,
                'nombre' => 'Centro de Actualización del Magisterio',
                'direccion_texto' => 'Calle 29 y Juárez #103. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 128,
                'ente_id' => 329,
                'nombre' => 'Centro de Capacitación y Desarrollo CECADE (SH)',
                'direccion_texto' => 'Calle Rosales #1500. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 129,
                'ente_id' => 96,
                'nombre' => 'Centro de Capacitación, Profesionalización y Certificación de la FGE',
                'direccion_texto' => 'Periferico Vicente Lombardo Toledano #4802. Horario: 9:00 - 15:00 | Colonia ID: 18379',
                'activo' => false,
            ],
            [
                'id' => 130,
                'ente_id' => 329,
                'nombre' => 'Centro de Conciliación Laboral - Cuauhtémoc',
                'direccion_texto' => 'Avenida Tecnológico #343. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 131,
                'ente_id' => 329,
                'nombre' => 'Centro de Conciliación Laboral - Delicias',
                'direccion_texto' => 'Avenida 20 de Noviembre y Ave. 50 Aniversario #2515. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 132,
                'ente_id' => 329,
                'nombre' => 'Centro de Conciliación Laboral - Nuevo Casas Grandes',
                'direccion_texto' => 'Avenida Constitución (entre Emilio Carranza y Galeana) #903. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 133,
                'ente_id' => 329,
                'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Chihuahua',
                'direccion_texto' => 'Avenida Central (Tabalaopa) #8901. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
            [
                'id' => 134,
                'ente_id' => 329,
                'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Cuauhtémoc',
                'direccion_texto' => 'Avenida Ingeniería #5270. Horario: 9:00 - 15:00 | Colonia ID: 73144',
                'activo' => true,
            ],
        ];

        DB::table('sedes')->insert($sedes);
    }
}