<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SedeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sedes = [
            ['id' => 1, 'ente_id' => 12, 'nombre' => 'SSPE / Transporte ACTUALIZAR', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 2, 'ente_id' => 2, 'nombre' => 'Administradora de Servicios Aeroportuarios de Chihuahua S.A. de C.V', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 3, 'ente_id' => 12, 'nombre' => 'Administrativo - Dirección de Transporte Cd. Juárez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 4, 'ente_id' => 15, 'nombre' => 'Administrativo Medidas Judiciales Zona Occidente Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 5, 'ente_id' => 4, 'nombre' => 'Agencia Estatal de Desarrollo Energético', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 6, 'ente_id' => 15, 'nombre' => 'Agencia Estatal de Investigación', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 7, 'ente_id' => 15, 'nombre' => 'Agencia Estatal de Investigación en Guachochi (Policía Estatal Única)', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 8, 'ente_id' => 36, 'nombre' => 'Almacén Central del ICHISAL', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 9, 'ente_id' => 7, 'nombre' => 'Almacén de Infraestructura Secretaría de Educación y Deporte', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 10, 'ente_id' => 3, 'nombre' => 'Almacén de Valores de Recaudación de Rentas (Antes Bodega de Embargos)', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 11, 'ente_id' => 2, 'nombre' => 'Almacén General', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 12, 'ente_id' => 2, 'nombre' => 'Almacenes Distribuidora de la Frontera S. A.', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 13, 'ente_id' => 2, 'nombre' => 'Américas', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 14, 'ente_id' => 36, 'nombre' => 'Antiguo Hospital Infantil', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 15, 'ente_id' => 10, 'nombre' => 'Apoyo a Dependencias (SCOP)', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 16, 'ente_id' => 2, 'nombre' => 'Archivo General del Estado de Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 17, 'ente_id' => 2, 'nombre' => 'Archivo General Juárez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 18, 'ente_id' => 2, 'nombre' => 'Archivo Notariado - Bodega de libros', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 19, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Catedral', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 20, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Creel', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 21, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) Parral', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 22, 'ente_id' => 250, 'nombre' => 'Arte Popular Chihuahua (FODARCH) PRONAF', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 24, 'ente_id' => 2, 'nombre' => 'ASP de Juárez S. A. de C. V.', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 25, 'ente_id' => 2, 'nombre' => 'At&T', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 26, 'ente_id' => 110, 'nombre' => 'Atención a Víctimas Plaza Greca', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 27, 'ente_id' => 5, 'nombre' => 'Atención para las Personas Adulto Mayor y MACHI - Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 28, 'ente_id' => 2, 'nombre' => 'Bafar Santa Anita Big Game Hunting S. de R. L. de C. V.', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 29, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 30, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Bahuichivo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 31, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Basaseachi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 32, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Galeana', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 33, 'ente_id' => 12, 'nombre' => 'Base de Operaciones en Madera', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 34, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Gomez Farías', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 35, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Guerrero', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 36, 'ente_id' => 12, 'nombre' => 'Base de Operaciones Namiquipa', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 37, 'ente_id' => 2, 'nombre' => 'Bodega', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 38, 'ente_id' => 3, 'nombre' => 'Bodega Bienes Muebles', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 39, 'ente_id' => 15, 'nombre' => 'Bodega de Archivo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 40, 'ente_id' => 15, 'nombre' => 'Bodega de Evidencias', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 41, 'ente_id' => 2, 'nombre' => 'Bogotá', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 42, 'ente_id' => 10, 'nombre' => 'Boquilla de Villa (SCOP)', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 43, 'ente_id' => 2, 'nombre' => 'Bufete Jurídico Universitario', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 44, 'ente_id' => 130, 'nombre' => 'Buró de Convenciones Buró de Convenciones A.C. - Cd. Juárez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 45, 'ente_id' => 12, 'nombre' => 'C 4 - Camargo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 46, 'ente_id' => 12, 'nombre' => 'C-4 Zona Norte.', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 47, 'ente_id' => 3, 'nombre' => 'Carreteras de Cuota - Secretaría de Hacienda', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 48, 'ente_id' => 113, 'nombre' => 'Centro de Patrimonio Cultural Casa Chihuahua', 'direccion_texto' => 'Calle Libertad 901, Col. Centro, Chihuahua, Chih.', 'conmutador' => '614 429 3300', 'activo' => true],
            ['id' => 49, 'ente_id' => 1, 'nombre' => 'Casa de Gobierno', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 50, 'ente_id' => 9, 'nombre' => 'Casa de la Cultura en Guachochi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 51, 'ente_id' => 2, 'nombre' => 'Casa Particular', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 52, 'ente_id' => 2, 'nombre' => 'Casas Grandes', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 53, 'ente_id' => 3, 'nombre' => 'Caseta de Estacionamiento Allende', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 54, 'ente_id' => 3, 'nombre' => 'Caseta de Galeana', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 55, 'ente_id' => 12, 'nombre' => 'Caseta de Inspección Ganadera El Granillo - Depto. de Ganadería', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 56, 'ente_id' => 3, 'nombre' => 'Caseta Ojo Laguna', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 57, 'ente_id' => 3, 'nombre' => 'Caseta San Jerónimo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 58, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Jiménez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 59, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Parral Jiménez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 60, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 61, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Chihuahua Ojinaga', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 62, 'ente_id' => 3, 'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Cuota de Conchos Camargo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 63, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Sacramento', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 64, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo - Ingresos de Carreteras de Cuota de Savalza', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 65, 'ente_id' => 3, 'nombre' => 'Caseta y Modulo - Ingresos de Carreteras de Villa Ahumada', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 66, 'ente_id' => 3, 'nombre' => 'Caseta y Módulo Ingresos de Carreteras de Cuota de Saucillo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 67, 'ente_id' => 38, 'nombre' => 'CAVIM - ICHIMU - Guachochi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 68, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 02 La Junta', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 69, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 03 Valle de Allende', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 70, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 04 Guadalupe y Calvo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 71, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 05 San Juanito', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 72, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 06 Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 73, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 07 San Isidro', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 74, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 08 Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 75, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 09 Lomas de Poleo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 76, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 10 Gómez Farías', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 77, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 11 Ciudad del Conocimiento', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 78, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 12 Flores Magón', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 79, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 13 San Guillermo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 80, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 14 Villa Esperanza', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 81, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 15 Ascención', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 82, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 16 Le Barón', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 83, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 17 Baborigame', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 84, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 18 Villa Aldama', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 85, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 19 Industrias', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 86, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 20 Oriente', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 87, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 21 Riberas Chihuahua', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 88, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 22 Ayuntamiento', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 89, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 23 Riberas Juárez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 90, 'ente_id' => 29, 'nombre' => 'CECYT Plantel 24 Toribio Ortega', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 91, 'ente_id' => 29, 'nombre' => 'CECYTECH Dirección General', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 92, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 01 Turuachi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 93, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 02 El Vergel', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 94, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 03 Rocheachi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 95, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 04 Carichí', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 96, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 05 Tomochi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 97, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 06 Benito Juárez', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 98, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 09 Atascaderos', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 99, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 10 Samachique', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 100, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 11 Bahuichivo', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 101, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 12 Satevó', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 102, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 13 Naica', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 103, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 15 Mesa de San Rafael', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 104, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 17 Morelos', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 105, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 18 Valle del Rosario', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 106, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 19 Moris', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 107, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 20 Santa Isabel', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 108, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 22 Nonoava', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 109, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 23 San Francisco de Borja', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 110, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 24 Urique', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 111, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 25 Congregación Ortíz', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 112, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 26 Bachíniva', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 113, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 28 Ignacio Zaragoza', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 114, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 29 Ojo de Agua', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 115, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 30 Riva Palacio', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 116, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 31 Témoris', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 117, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 32 Janos', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 118, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 33 Matachí', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 119, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 34 San Rafael', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 120, 'ente_id' => 29, 'nombre' => 'CECYTECH EMSAD 35 Uruachi', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 121, 'ente_id' => 12, 'nombre' => 'CEDEFAM', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 122, 'ente_id' => 7, 'nombre' => 'CEDEX e Inspección de Zona 58', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 123, 'ente_id' => 3, 'nombre' => 'Centro Comercial Galerías Tec - Recaudación de Rentas', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 124, 'ente_id' => 9, 'nombre' => 'Centro Cultural Palacio de Alvarado', 'direccion_texto' => 'Calle Riva Palacio 2, Col. Centro, Hidalgo del Parral, Chih.', 'conmutador' => null, 'activo' => true],
            ['id' => 125, 'ente_id' => 9, 'nombre' => 'Centro Cultural Paso del Norte - Secretaría de Cultura Cd. Juárez', 'direccion_texto' => 'Anillo Envolvente del Pronaf s/n, Col. Progresista, Ciudad Juárez, Chih.', 'conmutador' => '656 617 6603', 'activo' => true],
            ['id' => 126, 'ente_id' => 9, 'nombre' => 'Centro Cultural Quinta Carolina', 'direccion_texto' => 'Calle Monte Everest esq. Av. Fedor Dostoyevsky, Col. Quintas Carolinas, Chihuahua, Chih.', 'conmutador' => '614 499 3442', 'activo' => true],
            ['id' => 127, 'ente_id' => 7, 'nombre' => 'Centro de Actualización del Magisterio', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 128, 'ente_id' => 3, 'nombre' => 'Centro de Capacitación y Desarrollo CECADE (SH)', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 129, 'ente_id' => 15, 'nombre' => 'Centro de Capacitación, Profesionalización y Certificación de la FGE', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
            ['id' => 130, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Cuauhtémoc', 'direccion_texto' => 'Av. Tecnológico 349, Local C, Cuauhtémoc, Chih.', 'conmutador' => '625 688 2946', 'activo' => true],
            ['id' => 131, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Delicias', 'direccion_texto' => 'Calle Primera Oriente 103, Sector Oriente 1, Delicias, Chih.', 'conmutador' => '639 688 1923', 'activo' => true],
            ['id' => 132, 'ente_id' => 8, 'nombre' => 'Centro de Conciliación Laboral - Nuevo Casas Grandes', 'direccion_texto' => 'Av. Constitución 903, Local 6, Col. Centro, Nuevo Casas Grandes, Chih.', 'conmutador' => '636 692 7674', 'activo' => true],
            ['id' => 133, 'ente_id' => 32, 'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Chihuahua', 'direccion_texto' => 'Av. Central 8901, Parque Industrial Chihuahua Sur, Chihuahua, Chih.', 'conmutador' => null, 'activo' => true],
            ['id' => 134, 'ente_id' => 32, 'nombre' => 'Centro de Entrenamiento en Alta Tecnología (CENALTEC) Plantel Cuauhtémoc', 'direccion_texto' => null, 'conmutador' => null, 'activo' => true],
        ];

        foreach ($sedes as $sede) {
            DB::table('sedes')->updateOrInsert(
                ['id' => $sede['id']],
                [
                    'ente_id' => $sede['ente_id'],
                    'nombre' => $sede['nombre'],
                    'direccion_texto' => $sede['direccion_texto'],
                    'conmutador' => $sede['conmutador'],
                    'activo' => $sede['activo'],
                ]
            );
        }
    }
}